### ISSUE TITLE
DisPro10-data, DisPro12-unique-id, MultipleControlLoops_SpecProduce examples fail

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#100]
Observed in #97 

Failures of **Test build** and **Torxakis build** are about DatChecker; I fixed them in #99 . But failing **DisPro** and **MultipleControlLoops** tests are weird; they don't look like timing issues.

DAT Report:

Checking development acceptance test output for file 17Aug_153942.21_DatOutput.datr
- TestCopyright:         PASS
**- Test build:            FAIL** *(DatChecker should be updated)*
**- Torxakis build:        FAIL** *(DatChecker should be updated)*
- SelfTests:             PASS
- TestExamps:
--- StimulusResponse Tests
----- StimulusResponse Test 1: PASS
----- StimulusResponse Test 2: PASS
----- StimulusResponse Test 3: PASS
----- StimulusResponse Test 4: PASS
----- StimulusResponse Test 5: PASS
--- CustomersOrders Tests
----- CustomersOrders Test: PASS
--- LuckyPeople Tests
----- LuckyPeople Test 1: PASS
----- LuckyPeople Test 2: PASS
--- Adder Tests
----- Adder Test 1 - Basic: PASS
----- Adder Test 2 - State Automation: PASS
----- Adder Test 3 - Parallel Adders: PASS
--- DispatchProcess Tests
----- DisPro01-processor Test: PASS
----- DisPro02-dispatch Test: PASS
----- DisPro03-processors Test: PASS
----- DisPro04-hide Test: PASS
----- DisPro05-data Test: PASS
----- DisPro05a-data-nohide Test: PASS
----- DisPro06-datapos Test: PASS
----- DisPro06a-datapos-nohide Test: PASS
----- DisPro07-gcd Test: PASS
----- DisPro08-gcdpurp Test: PASS
----- DisPro09-multiproc Test: PASS
**----- DisPro10-data Test: FAIL**
**----- DisPro12-unique-id Test: FAIL**
----- DisPro12-unique-id_Wrong Test: PASS
----- DisPro12-unique-id_Right Test: PASS
--- ControlLoop Tests
----- ControlLoopModel Test: PASS
**----- MultipleControlLoops_SpecProduce Test: FAIL**
----- MultipleControlLoops_SpecMeasure Test: PASS
----- MultipleControlLoops_SpecCorrect Test: PASS
----- MultipleControlLoops_Spec Test: PASS
--- Echo Tests
----- Echo Stepper Test: PASS
----- Echo Simulator Test: PASS
--- Moving Arms Tests
----- MovingArms Stepper Test: PASS
----- MovingArms_Purpose Stepper Test: PASS
--- Point Tests
----- Point Stepper Test: PASS
----- Point_Purpose Stepper Test: PASS
--- Queue Tests
----- Queue Stepper Test: PASS
----- Queue_Lossy Stepper Test: PASS
----- Queue SUT Test: PASS
----- QueueStAut Stepper Test: PASS
----- QueueStAut_Lossy Stepper Test: PASS
--- ReadWriteConflict Tests
----- ReadWrite Stepper Test: PASS
----- ReadWrite7 Stepper Test: PASS
----- ReadWriteAdvanced Stepper Test: PASS
Checking finished

DatOutput
[17Aug_153942.21_DatOutput.datr.txt](https://github.com/TorXakis/TorXakis/files/1205140/17Aug_153942.21_DatOutput.datr.txt)

**Comment by keremispirli** [comment]
Ran them one by one to get all (including smt2) logs of failures.

MultipleControlLoops_SpecProduce
```
TXS >>  txsserver starting: "PC-14414.tsn.tno.nl" : 9876
TXS >>  Solver initialized : Z3 [4.5.1 - build hashcode 1f29cebd4df6]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  C:\Repos\TorXakis\\examps\ControlLoop\\MultipleControlLoops.txs
TXS <<  TXS >>  Stepper started
TXS <<  TXS >>  .....1: Act { { ( In_ProduceCmd, [ 0 C_ProduceCmd(C_ProductId(1),C_RecipeId(16)) ] ) } }
TXS >>  .....2: Act { { ( In_ProduceCmd, [ 0 C_ProduceCmd(C_ProductId(1),C_RecipeId(-38)) ] ) } }
TXS >>  .....3: Act { { ( In_ProduceMaterial, [ 0 C_BatchInfo(C_ProductId(1),C_BatchSize(50)) ] ) } }

TXS >>  cannot do action
TXS >>  FAIL: Act { { ( In_ProduceMaterial, [ 0 C_BatchInfo(C_ProductId(1),C_BatchSize(50)) ] ) } }
TXS <<  TXS <<  TXS >>  txsserver closing "PC-14414.tsn.tno.nl" : 9876
```
[MultipleControlLoops_SpecProduce.zip](https://github.com/TorXakis/TorXakis/files/1207617/MultipleControlLoops_SpecProduce.zip)

DisPro10-data
```
TXS >>  txsserver starting: "PC-14414.tsn.tno.nl" : 9876
TXS >>  Solver initialized : Z3 [4.5.1 - build hashcode 1f29cebd4df6]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  C:\Repos\TorXakis\\examps\DispatchProcess\spec\DisPro10-data.txs
TXS <<  TXS >>  Tester started
TXS <<  TXS >>  .....1: IN: Act { { ( Job, [ JobData(32,"FL4a",43,40) ] ) } }
TXS >>  .....2: IN: Act { { ( Job, [ JobData(84,"PC2",67,22) ] ) } }
TXS >>  .....3: IN: Act { { ( Job, [ JobData(76,"HP4",51,47) ] ) } }
TXS >>  .....4: OUT: Act { { ( Finish, [ JobOut(32,1,1) ] ) } }
TXS >>  .....5: OUT: Act { { ( Finish, [ JobOut(84,2,1) ] ) } }
TXS >>  .....6: OUT: Act { { ( Finish, [ JobOut(76,3,1) ] ) } }
TXS >>  .....7: OUT: No Output (Quiescence)
TXS >>  Expected:
TXS >>  [ ( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(12,1,1) == $Finish$1420$0$1$ ) ] ) ...
...
TXS >>  FAIL: No Output (Quiescence)
TXS <<  TXS <<  TXS >>  txsserver closing "PC-14414.tsn.tno.nl" : 9876
```
[DisPro10-data.zip](https://github.com/TorXakis/TorXakis/files/1207646/DisPro10-data.zip)

DisPro12-unique-id
```
TXS >>  txsserver starting: "PC-14414.tsn.tno.nl" : 9876
TXS >>  Solver initialized : Z3 [4.5.1 - build hashcode 1f29cebd4df6]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  C:\Repos\TorXakis\\examps\DispatchProcess\spec\DisPro12-unique-id.txs
TXS <<  TXS >>  Tester started
TXS <<  TXS >>  .....1: IN: Act { { ( Job, [ JobData(55,"P42dp",28,56) ] ) } }
TXS >>  .....2: IN: Act { { ( Job, [ JobData(65,"H42db",77,46) ] ) } }
TXS >>  .....3: IN: Act { { ( Job, [ JobData(51,"Y42dp",37,35) ] ) } }
TXS >>  .....4: OUT: Act { { ( Finish, [ JobOut(55,1,28) ] ) } }
TXS >>  .....5: OUT: Act { { ( Finish, [ JobOut(65,2,1) ] ) } }
TXS >>  .....6: OUT: Act { { ( Finish, [ JobOut(51,3,1) ] ) } }
TXS >>  .....7: IN: Act { { ( Job, [ JobData(89,"Z04r",35,88) ] ) } }
TXS >>  .....8: OUT: Act { { ( Finish, [ JobOut(89,4,1) ] ) } }
TXS >>  Expected:
TXS >>  [ ( { Finish[ $Finish$1980$0$1$ ] }, [], [ ( JobOut(73,3,1) == $Finish$1980$0$1$ ) ] )...
...
TXS >>  FAIL: Act { { ( Finish, [ JobOut(89,4,1) ] ) } }
TXS <<  TXS <<  TXS >>  txsserver closing "PC-14414.tsn.tno.nl" : 9876
```
[DisPro12-unique-id.zip](https://github.com/TorXakis/TorXakis/files/1207660/DisPro12-unique-id.zip)

**Comment by capitanbatata** [comment]
What do we want to do with these broken tests? Do we fix them or do we remove them if they are not relevant anymore?

**Comment by capitanbatata** [comment]
`MultipleControlLoops_SpecProduce` seems to fail randomly. I got the same error as reported by @keremispirli.

**Comment by keremispirli** [comment]
Dispro-12 and MultipleControlLoops_SpecProduce examples are not fixed yet.

**Comment by keremispirli** [comment]
@tretmans We see that Dispro-10 is failing again with the same error, twice in a row locally.
Related part:
```
TXS >>  examps\DispatchProcess\spec\DisPro10-data.txs
TXS >>  Tester started
TXS >>  .....1: IN: Act { { ( Job, [ JobData(28,"TD2",81,66) ] ) } }
TXS >>  .....2: IN: Act { { ( Job, [ JobData(38,"DP4bdah",58,80) ] ) } }
TXS >>  .....3: IN: Act { { ( Job, [ JobData(66,"AD2",79,1) ] ) } }
TXS >>  .....4: OUT: Act { { ( Finish, [ JobOut(28,1,3) ] ) } }
TXS >>  .....5: OUT: Act { { ( Finish, [ JobOut(38,2,2) ] ) } }
TXS >>  .....6: OUT: Act { { ( Finish, [ JobOut(66,3,1) ] ) } }
TXS >>  .....7: OUT: No Output (Quiescence)
TXS >>  Expected:
TXS >>   [ ( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(8,1,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(74,2,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(66,3,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(38,4,2) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(28,5,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(8,2,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(74,1,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(66,3,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(38,4,2) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(28,5,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(8,3,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(74,1,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(66,2,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(38,4,2) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(28,5,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(8,1,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(66,2,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(74,3,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(38,4,2) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(28,5,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(8,3,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(74,2,3) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(66,1,1) == $Finish$1420$0$1$ ) ] )
( { Finish[ $Finish$1420$0$1$ ] }, [], [ ( JobOut(38,4,2) == $Finish$1420$0$1$ ) ] )
( { ......
```

Full Logs:
[Process_10_-_Data.zip](https://github.com/TorXakis/TorXakis/files/1270041/Process_10_-_Data.zip)

**Comment by keremispirli** [comment]
DisPro-12 looks like it is fixed; I'm enabling it in sqatt.
SpecProduce problem is because of the Model.

This issue will be closed.
