### ISSUE TITLE
Update Control Loop example

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#104]
https://github.com/TorXakis/TorXakis/wiki/Modelling_Example_Control_Loop

**Comment by keremispirli** [comment]
changes:
https://github.com/TorXakis/TorXakis/wiki/Modelling_Example_Control_Loop/_compare/308676248e07fbbcaa9bbcacbdaba0940f147cd2...1c143f8c27cbc685f7ae68977c0bd5d3908c0b34

**Comment by capitanbatata** [comment]
The example looks good.
