### ISSUE TITLE
Update Lucky People example

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#106]
https://github.com/TorXakis/TorXakis/wiki/Modelling_Example_Lucky_People

**Comment by keremispirli** [comment]
Updated LuckyPeople example

Fixes images
Adds solution document, which explains all

Changes: https://github.com/TorXakis/TorXakis/wiki/Modelling_Example_Lucky_People/_compare/308676248e07fbbcaa9bbcacbdaba0940f147cd2...8b7b149742cfba7b668a7d45fa749df3978a86ef
Added: https://github.com/TorXakis/TorXakis/wiki/Modelling_Example_Lucky_People_Solution

**Comment by keremispirli** [comment]
Please review: @capitanbatata @pjljvandelaar

**Comment by capitanbatata** [comment]
- Can we change the title ("Modelling_Example_Lucky_People")
- In the table that follows "The input sequence is specified as follows:" maybe we need some headers in the columns to describe what each column means.
- I corrected some minor errors already.
- "You can find the solution here": I would say: "you can find **a** solution".

**Comment by pjljvandelaar** [comment]
Good work!

You can close the issue when Damian's comments are incorporated.

**Comment by keremispirli** [comment]
- Looks like the title is derived from file name; gotta use kebab-case to show spaces. Done.
- Added headers, also changed HTML table to GitHub Flavored MD table ( lack of headers was what prevented it before)
- Nice!
- "the" -> "a" - Done.
