### ISSUE TITLE
Test Selection / Replay

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#108]
There should be a TorXakis command (`trace txs`) for generating the trace to be replayed.

Acceptance criteria:
- On the wiki there should be an example describing the following steps after starting TorXakis with a model:
``` sh
# start the SUT
torxakis MyModel.txs
>>> tester MyModel SUT
>>> test 10
>>> trace txs $> MyTrace.txs
>>> exit
# reset the SUT 
torxakis MyModel MyTrace.txs
>>> tester MyModel MyTrace SUT
>>> test 10
# then you should observe the same steps.
```
- Add unit tests for the trace/replay features.
- Add an integration tests (preferably using the existing examples such as `Adder`).

**Comment by tretmans** [comment]
Code ready; tests and docs still to be done.

**Comment by capitanbatata** [comment]
The core will probably go under heavy changes, so I'm now writing unit tests for it yet, as discussed with @tretmans.
