### ISSUE TITLE
Performance / Symbolic Solver

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#133]

**Comment by pjljvandelaar** [comment]
Still to do:
 - [ ]  cstrFunctionCall : add parameter of type Map FuncId FuncDef containing all user defined functions. Needed when all arguments are constant values, and the function call can be (recursively) simplified using the associated function bodies.
 - [ ] cstrStrInRe: restructure value into eval and regextransformations packages. (should also include regex XSD to SmtLib representation).
 - [ ] Subst: replace partSubst and compSubst (also has  Map FuncId FuncDef argument)
 - [ ] Special package for connectiondef specific functions: toXml, fromXml, toString, fromString, and drop/take While (Not)

**Comment by pjljvandelaar** [comment]
subst: we couldn't replace partSubst and compSubst due to variable type replacement: from VarId to IVar and vice versa.

**Comment by pjljvandelaar** [comment]
When a var is replaced by a value, the resulting expression could be simplified as well.
For example, 
Vequal v 5 + replace v by 5 becomes true, and
Vequal v 5 + replace v by 90 becomes false.
Similar with Vite and accesors of Constructors.

* CreateExprXYZ must be made. These CreateExprXYZ functions can result in something else than an XYZ expressions when the arguments adhere to specific rules (as is known by the ExpressionXYZ).
Examples:
CreateEqual can result in a boolean value, when the arguments are both values.
CreateIfThenElse can result in an expression, when the conditional argument(s) resolve to True or False.
* Subst.hs only substitutes and doesn't simplify (when possible)
Different Variables exists, e.g. Variable () from Walue, Variable IVar from CTree, and Variable Ident from TxsDefs,
yet FuncDef has fixed argument types: [VarId] VExpr.
Consequently, simplifications that cross function definitions are NOT always possible.
An example of a simplification that cross a function defintion is
```
 third ( f(2,y) )
```
with 
```
f(x,y) = (x-y, 12-y, 4+x, 6*x*y)
```
(answer is 4+2 or just 6)
NOTE this expression can be rewritten as a constant, yet a straightforward eval wil fail!
* Multiple subst exists, see e.g. Walue.hs and Subst.hs
* Simplification and eval can share parts,
or eval can be removed: eval is 'useless' if everything is as simplified as possible.

**Comment by pjljvandelaar** [comment]
Closed since for remaining activities new issues are made #536 #537
