### ISSUE TITLE
Publish `sqatt-logs` from Travis

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#154]
`sqatt` publishes the test logs to a `sqatt-logs` folder. When a DA test goes wrong on CI it'd be nice to have these logs accessible for further analysis.  

Amazon AWS seems to be supported out of the box:
    - https://docs.travis-ci.com/user/uploading-artifacts/

But we have to request TNO for an account.

**Comment by capitanbatata** [comment]
We could also try FTP:
  - https://docs.travis-ci.com/user/deployment/custom/

**Comment by keremispirli** [comment]
We use [Semaphore CI](https://semaphoreci.com/capitanbatata/torxakis) now, which allows SSH into a failed build. This task is not needed anymore.
