### ISSUE TITLE
"Lucky People" example is tested for 1000 steps. Is that necessary?

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#157]
Do we need to test the second example of Lucky People for 1000 steps? If not we could greatly speedup our acceptance tests.

**Comment by pjljvandelaar** [comment]
If you randomly put males and female after one another, the chances of getting 5 female or male after each other is low.
In this past, we used this large number of steps to guarantee that we would test MMMMMF or FFFFFM.
Currently, we can use a test purpose to ensure this.
