### ISSUE TITLE
Release TxsCore as C library

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#176]
As already discussed earlier, we would like to release TxsCore as a library
that can be called from other languages than Haskell.
For example, c/c++ and PYTHON.
Of course, stack should execute the `build` process.....

See 
https://wiki.haskell.org/Calling_Haskell_from_C
https://github.com/ddfisher/HaPy
and maybe also
https://stackoverflow.com/questions/3859340/calling-haskell-from-c-code

**Comment by pjljvandelaar** [comment]
Maybe also look at: https://wiki.haskell.org/FFI_Introduction

**Comment by capitanbatata** [comment]
Do stakeholders prefer this over http or any AMPQ protocol?

**Comment by pjljvandelaar** [comment]
performance is often an issue, so http might be too slow...
I don't know AMPQ....

**Comment by capitanbatata** [comment]
>  I don't know AMPQ....: https://www.amqp.org/ I assume ;-)

Indeed. We could try for instance:
    https://www.rabbitmq.com/

I don't know what are the timing constraints but given our limited resources it'd be nice to come up with a solution that fits the largest number of stakeholders.

**Comment by keremispirli** [comment]
I found this: https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/win32-dlls.html#building-and-using-win32-dlls

Added *-shared* to **ghc-options** in "sys/core" and built, generates "HSdll.dll" and the import library "HSdll.dll.a".

Now checking if it's usable from C.

**Comment by HarmMunkESI** [comment]
Postpone to version 2017Q4.

**Comment by capitanbatata** [comment]
Based on the input provided by @HarmMunkESI, the only stakeholder that requested this does not have any plan to use this anymore. On top of that I think before doing this we should investigate what is the best way of connecting TorXakis with other SUT's and other user written functionality. So I'm closing this one for now.
