### ISSUE TITLE
Document the test-purpose feature

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#183]
The test-purpose feature is not documented.

Acceptance criteria:

- A new entry on our [wiki page](https://github.com/TorXakis/TorXakis/wiki) and [read-the-docs site](http://torxakis.readthedocs.io/en/feat-test-selection-replay/index.html) on test-purpose describing:
    - [x] the test purpose feature, ([here](https://github.com/TorXakis/TorXakis/wiki/PurpDefs))
    - [x] replay using the `trace` command, ([here](http://torxakis.readthedocs.io/en/feat-test-selection-replay/tutorial/trace-replay.html))
    - [ ] and general (non-probabilistic) flow.
- [x] Examples of the features above are provided on the ~wiki~ read-the-docs site. ([here](http://torxakis.readthedocs.io/en/feat-test-selection-replay/tutorial/trace-replay.html))

**Comment by keremispirli** [comment]
Damian added some documentation about saving trace of a test and replaying it using Test Purposes:
http://torxakis.readthedocs.io/en/feat-test-selection-replay/tutorial/trace-replay.html

We don't have docs for rest of the Acceptance Criteria though (e.g. PurpDef page, links to related examples)

**Comment by keremispirli** [comment]
Not delivered in Q3, moving to Q4.

**Comment by capitanbatata** [comment]
@keremispirli shouldn't we rephrase the acceptance criteria in terms of read-the docs? We do have examples of this functionality, so I'm now sure what is missing. Could you provide more details so that what needs to be done becomes more concrete and we can close this?

**Comment by keremispirli** [comment]
@capitanbatata 
- We don't have a page that explains PURPDEF keyword e.g. [ModelDefs](https://github.com/TorXakis/TorXakis/wiki/ModelDefs).
- I don't understand what "_general (non-probabilistic) flow_" means, so I don't know if we have that.
I think we have the rest. I updated the initial post.

**Comment by capitanbatata** [comment]
Ok, adding the page is clear. And for the "general (non-probabilistic) flow" I guess we need more details from @pjljvandelaar and @tretmans. Otherwise I'd like to remove this item and move on.

**Comment by keremispirli** [comment]
Added Test Purpose definition page: https://github.com/TorXakis/TorXakis/wiki/PurpDefs
