### ISSUE TITLE
Use cvc4 1.5 release 

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#184]
Acceptance criteria:

- [x] Unit tests that use cvc4 should run with version 1.5 (on Windows and Linux).
- [x] Add cvc4 1.5 release to [TorXakis' dependencies](https://github.com/TorXakis/Dependencies).
- [x] Run `sqatt` tests with cvc4 as solver (locally for now, if possible incorporate this into our CI workflow).
- [x] Update the installer to use cvc4 1.5 version. TorXakis/SourceWindowsInstaller#8

**Comment by capitanbatata** [comment]
It might be that some examples can't be solved with cvc4 (like customer orders), and that is ok.

**Comment by keremispirli** [comment]
CVC4 can't solve following examples:
### Control Loop
- Spec Measure (left overnight, in the morning CVC4 was running with 0% processor consumption)
- (testing continues)

**Comment by keremispirli** [comment]
I skipped the tests in previous post and launched a build in Semaphore to see Linux behaviour.
### Control Loop
**Spec Produce** fails - Stepper cannot start.
(testing in progress)
