### ISSUE TITLE
Make TorXakis v0.4.0 release

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#185]
Once all the main tasks associated with the Q3 milestones are completed we need to make a release for TorXakis.

**Comment by keremispirli** [comment]
- [ ] Create a PDF out of Modelling Examples wiki pages
- [ ] Update installer generation to include the PDF in documentation folder
- [ ] Create 0.4.0 installer

**Comment by keremispirli** [comment]
https://github.com/TorXakis/TorXakis/releases/tag/v0.4.0
