### ISSUE TITLE
menu fails

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#187]
When running torxakis,
using stepper Model
menu fails
as follows:
```
TXS <<  menu
TXS >>  iocoModelMenu without valid model
TXS >>  iocoModelMenu without valid model
TXS >>  []
```

**Comment by capitanbatata** [comment]
- Did you run TorXakis with a specific model?
- What is the expected output?

**Comment by pjljvandelaar** [comment]
Yes some proprietary models.
And we have seen it in all models....
The expected output is a menu: a list of valid actions.
