### ISSUE TITLE
document echo example

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#188]
The echo example has no documentation on the wiki or a READMe in the example directory.

observed by Kostas!

**Comment by keremispirli** [comment]
@pjljvandelaar @capitanbatata Please review:
https://github.com/TorXakis/TorXakis/wiki/Modelling-Example-Echo

**Comment by pjljvandelaar** [comment]
Great!

Note: We need to decide whether examples should be documented using README in the code archive to localize code and documentation better together.
