### ISSUE TITLE
Should TorXakis still work without a (proper) configuration file?

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#199]
We have default configuration in  sys/coreenv/src/Config.hs with #198 
This is a duplication of configuration data with the config file.
Do we want this?

**Comment by Mathijssen** [comment]
If you mean, is a configuration file mandatory, I would probably prefer no. I would prefer TorXakis to have default values, as this creates a kind of robustness.
However, if there is a configuration file present, one should consider an easy way to view all settings and also a means to indicate which settings are not the default ones

Read this as nice to haves from a user :-)

**Comment by keremispirli** [comment]
Thanks for the input @Mathijssen. I also experienced some benefits of having a default configuration in case no config file is available.

Closing.
