### ISSUE TITLE
Echo example use toString explicitly

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#2]
As a user I would like to experiment with Echo, and replace the String by another Type.
Currently, this results in parse errors.

When toString and fromString are used at the right places in Sim and Sut, this works immediately.

**Comment by PierreVDL** [comment]
(Unconstrained) Strings are problematic: 
Strings can contain the newline character '\n' 
yet TorXakis assumes line-based communication over Sockets!

**Comment by pjljvandelaar** [comment]
issue solved
