### ISSUE TITLE
How to write a TestPurpose for ReadWriteConflict?

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#205]
Pierre would like to have a test purpose that proves one can get all the output values [1..7] in ReadWriteConflict model.
Pierre:
I don't want all permutations, just the 7 different final read values.

we need reset SUT for this to work.
Yet, I am wondering whether we can already specify this property?

**Comment by pjljvandelaar** [comment]
Is this an example of a test objective which is not a test purpose?
Since I have no clue how to derive tests on basis of this test objective ....

**Comment by pjljvandelaar** [comment]
What about
```
PROCDEF output [Read, Write :: String # Int](n :: Int) HIT ::=
        Read ! "Final" ! n >-> Hit 
    ##
        Read ? x ? y [[ (x <> "Final") \/ (y <> n)]] >-> output [Read, Write](n)
    ##
        Write ? x ? y >-> output [Read, Write](n)
ENDDEF

PURPDEF HitAll ::= 
    CHAN IN   
    CHAN OUT  Read, Write

    GOAL Hit1 = output [Read, Write](1)
    GOAL Hit2 = output [Read, Write](2)
    GOAL Hit3 = output [Read, Write](3)
    GOAL Hit4 = output [Read, Write](4)
    GOAL Hit5 = output [Read, Write](5)
    GOAL Hit6 = output [Read, Write](6)
    GOAL Hit7 = output [Read, Write](7)
ENDDEF
```

By adding a loop, we might get to hit everything....but we definitely don't will provide any guidance!

**Comment by keremispirli** [comment]
Tried it...
TorXakis didn't want it;-)
```
TXS <<  tester Model HitAll Sut
TXS >>  Tester started
TXS <<  test 10
TXS >>  test purpose with only outputs not supported yet
TXS >>  No Verdict
```
