### ISSUE TITLE
TorXakis wrongly refuses action

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#217]
Looked deeper into the error got in SpecProduce (see #100).

When we run the following "purpose-model" with [MultipleControlLoops.txs](https://github.com/TorXakis/TorXakis/blob/develop/examps/ControlLoop/MultipleControlLoops.txs) model, 
```
PROCDEF replayProc [In_Correction :: Int # BatchId; In_ProduceCmd :: Int # ProduceCmd; In_ProduceMaterial :: Int # BatchInfo; Out_ProduceMaterial :: Int # BatchInfo; Out_ProduceReport :: Int # ProduceReport]() EXIT
::=

    In_ProduceCmd ! 0 ! C_ProduceCmd(C_ProductId(1),C_RecipeId(16))
>-> In_ProduceCmd ! 0 ! C_ProduceCmd(C_ProductId(1),C_RecipeId(-38))
>-> In_ProduceMaterial ! 0 ! C_BatchInfo(C_ProductId(1),C_BatchSize(50))
>-> EXIT
ENDDEF

MODELDEF  Replay
    ::=
        CHAN IN     In_Correction
        ,           In_ProduceCmd
        ,           In_ProduceMaterial
        CHAN OUT    Out_ProduceReport
        ,           Out_ProduceMaterial
    BEHAVIOUR
        replayProc [ In_Correction,In_ProduceCmd,In_ProduceMaterial,
                                       Out_ProduceMaterial,Out_ProduceReport] ( )
        |[ In_Correction,In_ProduceCmd,In_ProduceMaterial,
                                       Out_ProduceMaterial,Out_ProduceReport]| 
        produce [ In_Correction, In_ProduceCmd, In_ProduceMaterial, Out_ProduceReport, Out_ProduceMaterial ] ( 0 )
ENDDEF
```
TorXakis reports failure:
```
TXS <<  stepper Replay
TXS >>  Stepper started
TXS <<  step 4
TXS >>  .....1: Act { { ( In_ProduceCmd, [ 0 C_ProduceCmd(C_ProductId(1),C_RecipeId(16)) ] ) } }
TXS >>  .....2: Act { { ( In_ProduceCmd, [ 0 C_ProduceCmd(C_ProductId(1),C_RecipeId(-38)) ] ) } }
TXS >>  .....3: Act { { ( In_ProduceMaterial, [ 0 C_BatchInfo(C_ProductId(1),C_BatchSize(50)) ] ) } }
TXS >>  cannot do action
TXS >>  FAIL: Act { { ( In_ProduceMaterial, [ 0 C_BatchInfo(C_ProductId(1),C_BatchSize(50)) ] ) } }
```
According to the model the action is allowed. In due time, one of these outputs is expected:

`Out_ProduceReport ! 0 ! C_ProduceReport(C_BatchInfo(C_ProductId(1),C_BatchSize(50)),C_RecipeId(16),C_Time(X))`

**OR**

`Out_ProduceReport ! 0 ! C_ProduceReport(C_BatchInfo(C_ProductId(1),C_BatchSize(50)),C_RecipeId(-38),C_Time(X))`

**Comment by pjljvandelaar** [comment]
Happens in StepN

**Comment by pjljvandelaar** [comment]
The hidden action is non-unique, which is not allowed by TorXakis.
However, the error message is not related to this fact!

**Comment by tretmans** [comment]
The behaviour of TorXakis is not wrong:  There are hidden variables which do not have unique solutions, and TorXakis cannot deal with that. So what is wrong is that indeed the related error message was not printed.  This bug has been repaired.

**Comment by tretmans** [comment]
Additional remark:

Hidden variables:  [ $H_In_Cmd$$$2151$9$1$1$   $H_In_Cmd$$$2151$10$1$2$   ]

Solutions:

( "H_In_Cmd$$$2151$9$1$1" == 0 )
( "H_In_Cmd$$$2151$10$1$2" == "C_ProduceCmd$1396" ( "C_ProductId$1150" ( 1 ) "C_RecipeId$1349" (     16 ) ) )

( "H_In_Cmd$$$2151$9$1$1" == 0 )
( "H_In_Cmd$$$2151$10$1$2" == "C_ProduceCmd$1396" ( "C_ProductId$1150" ( 1 ) "C_RecipeId$1349",     ( -38 ) ) )

**Comment by tretmans** [comment]
Repaired error messages:

> $ torxakis MultipleControlLoops.txs Purp.txs 
> 
> TXS >>  TorXakis :: Model-Based Testing
> 
> TXS >>  txsserver starting: "PC-31093.tsn.tno.nl" : 9875
> TXS >>  Solver initialized : Z3 [4.5.1 - build hashcode 1f29cebd4df6]
> TXS >>  TxsCore initialized
> TXS >>  input files parsed:
> TXS >>  MultipleControlLoops.txs Purp.txs
> TXS <<  stepper Replay
> TXS >>  Stepper started
> TXS <<  step 5
> TXS >>  .....1: Act { { ( In_ProduceCmd, [ 0 C_ProduceCmd(C_ProductId(1),C_RecipeId(16)) ] ) } }
> TXS >>  .....2: Act { { ( In_ProduceCmd, [ 0 C_ProduceCmd(C_ProductId(1),C_RecipeId(-38)) ] ) } }
> TXS >>  .....3: Act { { ( In_ProduceMaterial, [ 0 C_BatchInfo(C_ProductId(1),C_BatchSize(50)) ] ) } }
> TXS >>  after: cannot find unique value for hidden variables
> TXS >>  stepN - cannot do action
> TXS >>  FAIL: Act { { ( In_ProduceMaterial, [ 0 C_BatchInfo(C_ProductId(1),C_BatchSize(50)) ] ) } }
> TXS <<  
>
