### ISSUE TITLE
Remove possibly failing tests from test set

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#227]
Some tests fail.
E.g due to possible time out and due to using the same id, causing a non-unique hidden step.
These tests should be removed from the development acceptance test set.

**Comment by capitanbatata** [comment]
Let's make a list of the tests that fail randomly. I can add:
  - spec produce
  - customer orders (sometimes it times out)

For customer orders we could make sure to use the same random seed, couldn't we?

And could we adjust the time out of control loop spec produce?

**Comment by keremispirli** [comment]
Maybe Echo simulator?
I have increased param_Sut_deltaTime to 5500 but it just keeps failing...

**Comment by keremispirli** [comment]
Moving Arms - Purpose Stepper also occasionally takes long, but I don't remember seeing it fail.

**Comment by keremispirli** [comment]
Control Loop - Multiple Loops stepper: https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/34
