### ISSUE TITLE
Starting TorXakis from a directory with no write permissions causes a "connection refused error"

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#242]
For example, trying to start TorXakis on my `/usr` folder gives rise to:

```
torxakis.sh: line 18: .txs.9876.log: Permission denied
txsui: Network.Socket.connect: <socket: 22>: does not exist (Connection refused)
```
Possible solution:

1. Get rid of the `.bat` and `.sh` scripts, and add make it possible for `txsui` to start a server if it is gonna run on the same machine. This will greatly simplify TorXakis usage for newcomers. We can modify the UI to search for the next available port if no port is given (and therefore assume that the user wants the UI to start the server locally).
2. Modify TorXakis server so that the logs are written to a standard location (like `$HOME/.torxakis/logs/`).

@pjljvandelaar I'm assigning this to you so that you can review the report. After that feel free to change the assignee.

**Comment by capitanbatata** [comment]
On branch `feat/start-txsserver-from-ui` the TorXakis server can be started from the UI, so by deprecating the batch files we can get rid of this problem. What do you think @pjljvandelaar

**Comment by pjljvandelaar** [comment]
I like the change.
Continue by removing the batch files: 
maybe let `torxakis.bat/sh` point to `txsui(.exe)`

**Comment by pjljvandelaar** [comment]
Should we put all info in `$HOME/.torxakis/` directory?
Thus 
* .torxakis.yaml
* .log files
* smt-log files
* etc.

**Comment by capitanbatata** [comment]
> maybe let torxakis.bat/sh point to txsui(.exe)

What do you mean exactly? Making symbolic links? Or just start `txsui` without arguments? Is there any issue with just removing the batch files?

> Should we put all info in $HOME/.torxakis/ directory?

I think it is a good idea, indeed.
