### ISSUE TITLE
Variables of stautdef can be used uninitialized

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#251]
we found out that variables of a stautdef can be used uninitialized.
See for example
MovingArms where `up` is not assigned a value (in that example it is not used, but no warning is issued!)
```

STAUTDEF singleAxisMovementSTAUTDEF[ UpX, DownX, StopX, MinX, MaxX, 
                                      UpY, DownY, StopY, MinY, MaxY, 
                                      UpZ, DownZ, StopZ, MinZ, MaxZ] () ::= 
       STATE  idle, moveX, moveY, moveZ 
        
       VAR    up :: Bool 
 
 
       INIT   idle 
 
 
       TRANS  idle  -> UpX   { up := True  }  ->  moveX 
...
ENDDEF
```

**Comment by pjljvandelaar** [comment]
Changing the `UpdateList` in TxsHappy.y to
```
UpdateList      -- :: { VEnv }
                -- top-level list of updates;
                -- attrs inh : inhNodeUid  : unique node identification
                --           : inhSortSigs : usable sorts
                --           : inhCstrSigs : usable constructors
                --           : inhFuncSigs : usable functions
                --           : inhVarSigs  : usable variables in value expressions
                --           : inhStVarSigs: usable variables in assignments = state variables
                -- attrs syn : synMaxUid   : maximum uid in whole subtree
                -- mirroring : -
                -- constrs   : exactly one unique update for each state variable
                --           : used objects shall be defined
              : {- empty -}
                {  $$.synMaxUid    = $$.inhNodeUid
                ;  $$ = Map.empty
                }
              | "{" "}"
                {  $$.synMaxUid    = $$.inhNodeUid
                ;  $$ = Map.empty
                }
              | Updates 
                {  $1.inhNodeUid   = $$.inhNodeUid + 1
                ;  $$.synMaxUid    = $1.synMaxUid
                ;  $1.inhSigs      = $$.inhSigs
                ;  $1.inhVarSigs   = $$.inhVarSigs
                ;  $1.inhStVarSigs = $$.inhStVarSigs
                ;  $$ = $1
                }
              | "{" Updates "}"
                {  $2.inhNodeUid   = $$.inhNodeUid + 1
                ;  $$.synMaxUid    = $2.synMaxUid
                ;  $2.inhSigs      = $$.inhSigs
                ;  $2.inhVarSigs   = $$.inhVarSigs
                ;  $2.inhStVarSigs = $$.inhStVarSigs
                ;  $$ = $2
                }
```
causes the following error
`TXS1015: No (unique) initial values for all state vars`.

So initial values are checked, yet the code of `UpdateList` adds an
identity relation ` Map.fromList [ (vid, cstrVar vid) | vid <- $$.inhStVarSigs ]`
which cause the initial value checking to incorrectly PASS when variables are NOT initialized.

**Comment by triantafyllidisk** [comment]
As a user i would prefer to get a warning instead of error when a variable is not initialized. This is because usually there might be variables that are used as "temp" variables and are always written with a value before been read. In that case i would rather not to initialize a variable with a dummy value.

**Comment by pjljvandelaar** [comment]
My pull request #382 fixes this issue.
However, it produces an error (i.s.o. a warning) when a variable is not initialized.
@triantafyllidisk should we make a separate issue for your requirement?

**Comment by triantafyllidisk** [comment]
Does this mean that the new version of TorXakis will output error when a variable is not initialized? In that case i am not willing to update yet to the new version (at least for main development) because then my models will not run. I will open a new issue the coming hours when i install the new version of TorXakis and test it.
