### ISSUE TITLE
Stepper hangs consuming all system memory on this example

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#268]
Consider the following `TorXakis` model:

```
CHANDEF ChanDefs ::=
    MyAct
ENDDEF

PROCDEF sequence[act]() ::=
   act >-> sequence[act]()
ENDDEF

PROCDEF synchronizedN[act](n :: Int) ::=
     ([[ n == 1 ]] =>> sequence[act]())
  ##
     ([[ n >  1 ]] =>> sequence[act]() |[act]| synchronizedN[act](n - 1))
ENDDEF

MODELDEF ForeverSynchronized3 ::=
    CHAN IN
    CHAN OUT MyAct
    BEHAVIOUR synchronizedN[MyAct](3)
ENDDEF
```

When running `TorXakis` with the command `stepper ForeverSynchronized3` `TorXakis` just hangs and eats up all the system memory.

**Comment by pjljvandelaar** [comment]
What is running? Txsserver or the problem solver?

**Comment by capitanbatata** [comment]
As @pjljvandelaar pointed out, this model will not terminate, since:

```
([[ n >  1 ]] =>> sequence[act]() |[act]| synchronizedN[act](n - 1))
```

is actually interpreted as

```
(([[ n >  1 ]] =>> sequence[act]()) |[act]| synchronizedN[act](n - 1))
```

`=>>` binds stronger than `|[act]|`, which means that the process won't stop when `n` is `1`.
