### ISSUE TITLE
cannot declare commandline variables anymore?

### ISSUE THREAD

**Issue by tretmans** [TorXakis/TorXakis#275]
TXS <<  var x::Bool
TXS >>  invalid reference to attribute 'synSigs'
TXS >>  CallStack (from HasCallStack):
TXS >>  error, called at .stack-work\dist\1f7101f2\build\TxsHappy.hs:3059:238 in front-0.2.1.0-4SSaJAgSDY15FH9QZqMreo:TxsHappy
TXS <<  var x::Int
TXS >>  invalid reference to attribute 'synSigs'
TXS >>  CallStack (from HasCallStack):
TXS >>  error, called at .stack-work\dist\1f7101f2\build\TxsHappy.hs:3059:238 in front-0.2.1.0-4SSaJAgSDY15FH9QZqMreo:TxsHappy
TXS <<

**Comment by pjljvandelaar** [comment]
what is expected from
```
>> var x :: Int
>> var x :: Bool
```
is this an error or does this hide/remove the integer declaration?

**Comment by pjljvandelaar** [comment]
The current behavior is
```
TXS <<  var x :: Int
TXS >>  [ x ]
TXS <<  var x :: Bool
TXS >>  double variable names: [ x ]
```

**Comment by pjljvandelaar** [comment]
```
TXS <<  eval (False /\ True)
TXS >>  False
```
However, still a bug
```
TXS <<  var x :: Bool
TXS >>  [ x ]
TXS <<  eval (False /\ x)
TXS >>
TXS >>  TXS0422: Operator not resolved: '"/\\"'
TXS >>  Argument 0: ValExpr {view = Vconst (Cbool {cBool = False})}
txsui: <socket: 456>: hGetLine: failed (No error)
```
content of log file
```
TXSSERVER RSP <<  MACK TXS0422: Operator not resolved: '"/\\"'
TXSSERVER RSP <<  MACK Argument 0: ValExpr {view = Vconst (Cbool {cBool = False}
)}
TXSSERVER RSP <<  MACK Argument 1: ValExpr {view = txsserver.exe:
TXS0430: Identifier not resolved: "x"
```

**Comment by pjljvandelaar** [comment]
strange 
the following works fine:
```
TXS <<  var x :: Int
TXS >>  [ x ]
TXS <<  solve (x > 0)
TXS >>  sat
TXS >>  x = 1
```

**Comment by pjljvandelaar** [comment]
It works:
```
TXS <<  var x :: Bool
TXS >>  [ x ]
TXS <<  eval (False /\ x)
TXS >>  False
```

**Comment by keremispirli** [comment]
Don't we need a unit test for this fix? If we broke it once...

**Comment by tretmans** [comment]
A test: yes. But at UI level I would say;
a test that uses commands  'var', 'val', éval', 'solve'.

**Comment by keremispirli** [comment]
Will be done in #286
