### ISSUE TITLE
Redmine to Github

### ISSUE THREAD

**Issue by tretmans** [TorXakis/TorXakis#276]
Check Redmine Issue List for inclusion in Github.

**Comment by keremispirli** [comment]
There are 189 open issues as of now. Redmine requires multiple steps to actually close issues. To do it manually, ~3min per issue is needed.
If we bulk import, then we'll have quite some duplicate issues in GitHub that we will have to manually check and discuss and close.
What would be the best approach? How much time do we want to spend on this?

**Comment by pjljvandelaar** [comment]
I moved quite some issues manually already.
I propose to move the last 150 automatically: see
* https://github.com/iqss/redmine2github
* https://blogs.harvard.edu/rprasad/2014/07/10/moving-from-redmine-to-github-issues/

why?
* only issues by Jan and me remaining, so we will understand them quite well ;-)
* saves time

**Comment by pjljvandelaar** [comment]
done!

Only issue 2273 remains.
The non-confidential info is copy to #417
