### ISSUE TITLE
wobbly tests once more

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#284]
We have to do something about:
```
1) Examples.All, Dispatch Process, Process 12 - Unique ID (Wrong)
 expected: Right ()
 but got: Left (TestExpectationError "Did not get expected result Fail")
```

Because trying to get two the same ids after each other might fail.... but the test should succeed!

We must start using test purpose and accept halted as well!

**Comment by capitanbatata** [comment]
Do you know why setting the same random seed won’t help?

**Comment by keremispirli** [comment]
Related to #238 
Will be fixed in #289

**Comment by pjljvandelaar** [comment]
Is tonigts failing test a wobbly test.
Seems issue with socket....

**Comment by capitanbatata** [comment]
Which tests do you mean? I guess the one on my branch. Bear in mind that the branch is work in progress.

We're also in gitter BTW ;)

**Comment by pjljvandelaar** [comment]
No I mean the nightly tests, that run at 10 o'clock

**Comment by pjljvandelaar** [comment]
https://semaphoreci.com/capitanbatata/torxakis/branches/develop

**Comment by pjljvandelaar** [comment]
See how some tests pass while others fail...

**Comment by keremispirli** [comment]
It's always the same test: _Moving Arms #model Restricted Axis Purpose Test (input eagerness 0)_
I created a new issue for it: #561

**Comment by pjljvandelaar** [comment]
Last night build failed due to socket address already in use....
We should reopen this issue or create a new one...
See https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/239

**Comment by capitanbatata** [comment]
I propose to open a new issue with that specific error. That will give us more focus and a beter definition of done.

**Comment by pjljvandelaar** [comment]
done see #578
