### ISSUE TITLE
Assigning param_Sut_deltaTime breaks tester

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#29]
TXS <<  param param_Sut_deltaTime 4000
TXS >>  param_Sut_deltaTime = 4000
TXS <<  tester Model Sut
txsui: <socket: 584>: hGetLine: failed (No error)

stepper and simulator work fine. If param is not assigned, tester also works fine.
Tried with Adder and CustomersOrders examples.

**Comment by pjljvandelaar** [comment]
What is the message in .txs.$portnr$.err.log file?

**Comment by keremispirli** [comment]
TXSSERVER RSP <<  MACK input files parsed:
TXSSERVER RSP <<  MACK Adder.txs
TXSSERVER RSP <<  PACK INIT
TXSSERVER CMD >>  PARAM param_Sut_deltaTime 4000
TXSSERVER RSP <<  MACK param_Sut_deltaTime = 4000
TXSSERVER RSP <<  PACK PARAM
TXSSERVER CMD >>  TESTER Adder Sut
txsserver.exe: connect: failed (Connection refused (WSAECONNREFUSED))

**Comment by pjljvandelaar** [comment]
Did you start the Sut (java adder)?

**Comment by keremispirli** [comment]
I was trying with Simulator, but now I tried and it works. I probably got confused and forgot to ensure there's some sut on the other side.

closing this.
