### ISSUE TITLE
`stack.yaml` files in the `sys` packages are outdated

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#32]
Building the individual packages with stack does not work since the `stack.yaml` configuration is outdated. A problem seems to be that the `packages` section point to non-existing directories.

If the `stack.yaml` files are not needed I'd propose to remove this, since this will confuse `stack` aware IDE's like Intero or ghc-mod.

If they are needed we need to correct them, and find a workaround for IDE integration.

**Comment by pjljvandelaar** [comment]
I used the packages of the individual package to run only their tests.
I like this functionality, yet I don't know if alternatives for this exists.

**Comment by capitanbatata** [comment]
What about running `stack <package-name>`? from the root folder, e.g.:

```
$ stack.exe test behave
behave-0.2.1.0: test (suite: behave-test)

Cases: 16870  Tried: 16870  Errors: 0  Failures: 0
```

If testing are the only reason for keeping the individual `stack.yaml` files we could just remove them then.

**Comment by pjljvandelaar** [comment]
Was not aware of this possibility: So I have no problem to remove them!
@kerem so no change to Development Acceptence Test needed!

**Comment by capitanbatata** [comment]
Ok, I'll make a branch and submit a PR.
