### ISSUE TITLE
The TorXakis server will fail to find a file relative to the UI if the former was started in a different directory

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#341]
If `txsserver` and `txsui` are started in different directories, then the files passed to the `txsui` have to be relative to the `txsserver` working directory. This is quite confusing.

**Comment by pjljvandelaar** [comment]
Solution: ui calls server with absolute path

**Comment by capitanbatata** [comment]
I wouldn't consider this a solution. A workaround at most.

**Comment by capitanbatata** [comment]
Oh, now I see what you mean. But if the server and ui are in separate machines then this won't work. The ui should stream the file contents to the server. But all in all, The question is whether this server client architecture makes sense...

**Comment by pjljvandelaar** [comment]
I totally agreeing that we might want to make a server-library / component and let the UI use this server-library / component by doing a function call...
Of course, the exotic situation that server and ui are on separate machines will no longer be possible.
Yet, I wonder whether it is currently even possible....

**Comment by capitanbatata** [comment]
> Of course, the exotic situation that server and ui are on separate machines will no longer be possible.
Yet, I wonder whether it is currently even possible....

Currently it is not: "localhost" is hardcoded as hostname :scream_cat: So it seems we have a convoluted solution for nothing. As such, it does not make sense to investigate whether we can stream the contents of the model file to the server (instead of having the server read them from file). So I'm marking this as "wontfix". All in all, I hope most users will be using the `txsui` without a port number, which will spawn a `txsserver` isntance, and workaround this problem.

**Comment by pjljvandelaar** [comment]
# TorXakis separation in txsserver txsui not perfect
