### ISSUE TITLE
Add support for dynamically changing SMT solver 

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#35]
Currently the SMT solver to be used is hard-wired in `TxsCore` at `txsInit`.  We need to make this configurable when starting TorXakis.

Blocks #28.

**Comment by capitanbatata** [comment]
So far the best option seems to be [Configurator](http://hackage.haskell.org/package/configurator-0.3.0.0/docs/Data-Configurator.html). @pjljvandelaar do you have any thoughts on it? Are there any requirements this won't cover?

**Comment by capitanbatata** [comment]
It also seems like we need to add support for a command line argument that points to the location of the configuration file.

**Comment by pjljvandelaar** [comment]
One desire is that the dependency occurs in the latest lts.
https://www.stackage.org/lts
This keeps managing the dependencies easy!

Specifying the start-up parameters could occur in a config file and/or using command line arguments.
I would like a default place or default places for the config file.
E.g. look for config file in the following location [current directory, user home directory, torxakis installation directory].
Of course, you could overwrite this using a command line argument. Like stack,
`--stack-yaml STACK-YAML  Override project stack.yaml file`

For now, start as simple as possible.
Add extensions, like command line arguments later.
