### ISSUE TITLE
History remembers same command multiple time

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#402]
As I user, I like that repeating the same command does not change the history.

For example,
Currently all steps in
``` 
stepper Model
step 100
step 100
step 100
param param_IncrementChoice_IntRange 100
step 100
step 100
step 100
param param_IncrementChoice_IntPower 1
step 100
step 100
step 100
step 100
step 100
step 100
```
are remembered.
Yet I would like that all duplicates are removed,
such that I can more quickly browse through the history.

**Comment by capitanbatata** [comment]
Done: https://github.com/TorXakis/TorXakis/pull/411

This is the kind of fix one does while your toddler takes a nap :laughing:
