### ISSUE TITLE
Include git hash in info

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#404]
As I user, I would like to know what code was used to make the torxakis version I am currently using.
So info should return the git SHA-1 hash.
(Like is done by Z3).

**Comment by keremispirli** [comment]
Issue moved to [TorXakis/SourceWindowsInstaller #19](https://github.com/TorXakis/SourceWindowsInstaller/issues/19) via [**ZenHub**](https://www.zenhub.com/)
