### ISSUE TITLE
make stack issue

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#415]
We regularly have issues like: 
https://ci.appveyor.com/project/keremispirli/torxakis

I think we keep on hitting the same stack issue.
We should make insert an issue into the stack project.
https://github.com/commercialhaskell/stack/issues

**Comment by capitanbatata** [comment]
There's already [an issue](https://github.com/commercialhaskell/stack/issues/1917) reported on the stack repository, which was closed as a support ticket. There is also [another one](https://github.com/commercialhaskell/stack/issues/3492) reported, which is open. So I guess not much to do in this issue other than joining the conversation on the latter issue.

**Comment by keremispirli** [comment]
I'm reporting there now :)
