### ISSUE TITLE
CVC4 solver is hardcoded

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#47]
SMTInternal.hs - L41:
```
cmdCVC4 = proc "cvc4-2017-06-13-win32-opt"
```

We should parametrize this.

**Comment by pjljvandelaar** [comment]
Same for the arguments to CVC4 and Z3

**Comment by pjljvandelaar** [comment]
Introduced a bug, since CVC4 at my machine and at Travis differed.
Conclusion: raise the priority!

**Comment by capitanbatata** [comment]
I would propose that we rename the executables in our systems (both on Windows and Travis) to `cvc4` and `z3`, and have TorXakis use these names by default. I'm working on issue #66 and there I need to detect wether these solvers are installed before running any tests, and I would like to avoid having to hardcode platform dependent names there as well.

**Comment by keremispirli** [comment]
z3 is already named *z3.exe*
cvc4 is named *cvc4-1.5-win32-opt.exe*; it can definitely use some make up :)

On the other hand, in order to be platform-independent it wouldn't be enough to rename executables since in Windows they will still have *.exe* extension. I think it'll be better to use a configuration file to avoid using name of the actual executable in code.

**Comment by capitanbatata** [comment]
The `.exe` prefix can be added by just checking the platform TorXakis is running. We still need to add a configuration support for it, but `cvc4-1.5-win32-opt.exe` is not a good default I think. So I'd propose having `z3` and `cvc4` by default.

**Comment by pjljvandelaar** [comment]
We didn't use the extension .exe, since on Linux it is invalid and on windows it is not needed.

**Comment by pjljvandelaar** [comment]
I would like to leave the naming to the user.
I am in favor of a config file to map cvc4/z3 to the real name!

**Comment by capitanbatata** [comment]
> We didn't use the extension .exe, since on Linux it is invalid and on windows it is not needed.
We don't need to specify the `.exe` suffix, this one can be added depending on the host operating system.

>  I am in favor of a config file to map cvc4/z3 to the real name!
I agree. But we do need to use sensible defaults instead of `cvc4-1.5-win32-opt.exe`

**Comment by pjljvandelaar** [comment]
I noticed a case where the .exe suffix must be added: `cvc4-1.5-win32-opt`
This name already contains a '.', so no .exe extension is added anymore by Haskell/Windows platofrm!

**Comment by capitanbatata** [comment]
Why is the extension needed in this case?

**Comment by pjljvandelaar** [comment]
on windows cvc4-1.5-win32-opt is not found on the path,
since due to the dot, it doesn't search for cvc4-1.5-win32-opt with the extension exe

**Comment by capitanbatata** [comment]
Ok, should I pick this issue up then?

**Comment by pjljvandelaar** [comment]
You should only pick it up when we also support a configuration file: I don't anybody wants to type in both the smt solver name and the smt solver commands on the TorXakis command line!

**Comment by pjljvandelaar** [comment]
Yet, I would like to use Z3 with the Z3Str3 solver....
and play more with the 1.5 release of cvc4!

**Comment by capitanbatata** [comment]
> You should only pick it up when we also support a configuration file: I don't anybody wants to type in both the smt solver name and the smt solver commands on the TorXakis command line!

It shouldn't be necessary to pass the SMT executable name explicitly. TorXakis is using a default value already (albeit a hardcoded one). I propose to change this as follows:

- Remove the string `"cvc4-2017-06-13-win32-opt"` from `SMTInternal`.
- Use by default the string `cvc4` as executable name.
 - Provide options to change the default values for the SMT commands:
    - In a configuration file
    - Via command line options

So I propose that I tackle this in one go so that we can close this.

**Comment by capitanbatata** [comment]
We need to make sure that increment choice is the default as mentioned in this issue https://github.com/TorXakis/TorXakis/issues/181.

**Comment by pjljvandelaar** [comment]
Why does sqatt still refer to this issue?
It is solved!

**Comment by keremispirli** [comment]
I'm creating a new issue to implement `checkSMTSolvers` in `sqatt`.
