### ISSUE TITLE
detection of doubly defined entities

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#483]
Dubbele functies worden hier WEL statisch gedetecteerd;
dubbele process defs NIET; pas bij gebruik wordt ontdekt dat p niet uniek gedefinieerd is.

Willen we dat?
```
FUNCDEF f (a,b::Int) :: Int ::= a+b ENDDEF

FUNCDEF f (x,y::Int) :: Int ::= x+y ENDDEF

PROCDEF p [G] ()
 ::= STOP
ENDDEF

PROCDEF p [G] ()
 ::= STOP
ENDDEF

MODELDEF S ::=
 CHAN IN
 CHAN OUT K
 BEHAVIOUR
 p [K] ()
ENDDEF
```

**Comment by dnadales** [comment]
Now, the new compiler will give an error in both cases: when ambiguous functions are used, and when ambiguous process are used.

So the behavior is consistent, but less restrictive.

**Comment by pjljvandelaar** [comment]
New compiler should be more restrictive ;-)
Also for channels and parameters.
