### ISSUE TITLE
Spaces in model path not permitted

### ISSUE THREAD

**Issue by JFoederer** [TorXakis/TorXakis#495]
To reproduce create a folder with a space in the name. In this example 'folder oops with space'
Locate a .txs model in that folder and start TorXakis to run this model.

Interaction:
d:\temp>torxakis "D:\temp\folder oops with space\model\SRfinite.txs"
oops was unexpected at this time.
d:\temp>

**Comment by pjljvandelaar** [comment]
Can one use `"` with file paths?

**Comment by pjljvandelaar** [comment]
problem is located in communication between torxakis and txsserver. In particular the `INIT` command.
