### ISSUE TITLE
Line numbers are often not present in error reporting for a model

### ISSUE THREAD

**Issue by JFoederer** [TorXakis/TorXakis#496]
While developing TorXakis models you make a mistake every now and then. For some obvious syntax errors you get a line number reported, very useful! But for most errors you are left in the dark about where to start searching for the mistake. Now that our models are getting bigger this is really becoming an issue! Please provide a location for all errors in the model.

**Comment by petravandenbos** [comment]
The error message given in these situations then mentions that something is wrong with the operator /\ or ++, but as these operators occur very often in the model, you have no clue where to look

**Comment by dnadales** [comment]
Hi, I just submitted a pull request with a [new compiler](https://github.com/TorXakis/TorXakis/pull/741) which produces more information. Could you give it a try and submit issues when an error is not useful enough? Then we can improve the error messages in a case by case basis. Thanks!

**Comment by JFoederer** [comment]
Thanks for the update. I’ll give a try!

Kind regards,
Johan Foederer
Océ-Technologies • Software Test Automation specialist

**Comment by pjljvandelaar** [comment]
permanently removed sensitive info.
