### ISSUE TITLE
SUT - Remote Procedure Call

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#518]
Connecting TorXakis via a Remote Procedure Call to the SUT is desired.

See https://en.wikipedia.org/wiki/Remote_procedure_call

**Comment by capitanbatata** [comment]
There are a lot of alternatives for implementing RPC, some of them outdated, some of them obsolete, and some of them language specific. Do we know **who** is desiring this feature, which languages are they going to use, and how? I think we need examples of how this would look like.

Also I wonder whether this has any advantages over communicating with the SUT via a message-queue (RabbitMQ, ZeroMQ) plus some serialization framework such as Google protocol buffers.

**Comment by pjljvandelaar** [comment]
When we   support #519 users can implement RPC themselves.
No direct request from users.
To focus our limited resources we close this issue.
