### ISSUE TITLE
link doesn't work

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#543]
In the section show item of TxsCore (https://torxakis.github.io/TorXakis/doc/core-0.2.1.0/TxsCore.html#g:26),
the link for name (https://torxakis.github.io/TorXakis/doc/core-0.2.1.0/name) doesn't work!

```
404

File not found

The site configured at this address does not contain the requested file. 

If this is your site, make sure that the filename case matches the URL.
 For root URLs (like http://example.com/) you must provide an index.html file. 

Read the full documentation for more information about using GitHub Pages. 

GitHub Status — @githubstatus 
```

**Comment by keremispirli** [comment]
That's because of the comments:
```
txsShow :: String               -- ^ kind of item to be shown.
        -> String               -- ^ name of item to be shown.
                                --   Valid items are "tdefs", "state",
                                --   "model", "mapper", "purp", "modeldef" <name>,
                                --   "mapperdef" <name>, and "purpdef" <name>.
        -> IOC.IOC String
```
Apparently haddock interprets angle brackets as internal links.

**Comment by pjljvandelaar** [comment]
How can we escape <name>?

**Comment by pjljvandelaar** [comment]
@tretmans [txsShow's documentation](https://torxakis.github.io/TorXakis/doc/core-0.2.1.0/TxsCore.html#g:29)
 links now to
https://torxakis.github.io/TorXakis/doc/valexpr-0.0.1.0/VarId.html#v:name is this correct

**Comment by pjljvandelaar** [comment]
We should better read the [Markup page](https://www.haskell.org/haddock/doc/html/ch03s08.html)
