### ISSUE TITLE
z3 4.6.0 is out

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#570]
We should benchmark and decide if we want to upgrade.

https://github.com/Z3Prover/z3/releases/tag/z3-4.6.0

**Comment by pjljvandelaar** [comment]
Benchmark not necessary. . 
We want our bugs solved so we have to keep up with the latest release.

**Comment by keremispirli** [comment]
Pierre tested z3 4.6.0 and CVC4 latest development version; both seem OK.

**Comment by pjljvandelaar** [comment]
I prefer to add new problem solvers after a release:
we can test `torxakis` together with these new problem solvers almost a quarter before we make a new `torxakis` release.
I assume that real issues will already have been found by that time!

**Comment by pjljvandelaar** [comment]
@kerem didn't you do this? So can this issue be closed?

**Comment by keremispirli** [comment]
@pjljvandelaar No I didn't; I thought you wanted it to be added after the release?

**Comment by pjljvandelaar** [comment]
Didn't we not just release 0.5.0?
