### ISSUE TITLE
Fix all the compiler warnings introduced by the `lpe` branch

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#576]
The [`lpe` branch](https://github.com/TorXakis/TorXakis/pull/574) introduced a huge number of compiler warnings  that should be removed to help our efforts to raise the quality of TorXakis.

Right now, in every source file inside the `sys/lpe` folder, there are pragmas that disable all the warnings (which we treat as errors under normal circumstances):

```haskell
{-# OPTIONS_GHC -Wno-name-shadowing #-}
{-# OPTIONS_GHC -Wno-unused-matches #-}
{-# OPTIONS_GHC -Wno-incomplete-patterns #-}
{-# OPTIONS_GHC -Wno-unused-local-binds #-}
{-# OPTIONS_GHC -Wno-incomplete-patterns #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}
{-# OPTIONS_GHC -Wno-missing-signatures #-}
{-# OPTIONS_GHC -Wno-unused-top-binds #-}
```

All these warnings must be eliminated, and the corresponding`OPTIONS_GHC` lines must be also removed.

Bear in mind that we compile with the `--pedantic` flag, which, at the moment, amounts to compiling with the `-Werror -Wall` flags. So you might want to pass the `--pedantic` flag to stack when building to check that everything will build on our CI.

**Comment by pjljvandelaar** [comment]
- [ ] hlint
- [ ] warnings LPE.hs
- [ ] warnings LPEfunc.hs
- [ ] warnings in tests
