### ISSUE TITLE
nightly build fails

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#578]
One of the nightly builds failed due to socket address already in use....
See https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/239

**Comment by pjljvandelaar** [comment]
Also tonight the build failed.
https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/270
The simulator is finished before the tester....

**Comment by pjljvandelaar** [comment]
Is this due to the new z3 version?
See https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/266
Build 267 and 268

**Comment by keremispirli** [comment]
Caused by #561

**Comment by pjljvandelaar** [comment]
@keremispirli I think we need to be more precise:
Failing test due to the simulator which is finished before the tester is caused by #561 
The first reported issue (socket address already in use) is not

**Comment by pjljvandelaar** [comment]
What remains of this issue is a duplicate of #602
Do think it is useful to have two duplicates: so I close one (this one to be precise)
