### ISSUE TITLE
too many branches in archive

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#579]
We have many branches which complicates the situation for a new user/contributer.
See e.g.
![image](https://user-images.githubusercontent.com/18348654/36467920-57f7b0a0-16e1-11e8-8016-fbea33ee30fd.png)

Can we get rid of non-longer used branches?

**Comment by keremispirli** [comment]
I deleted the `feat/coveralls` branch that I have created for experiment. I don't have any other inactive branches.
@TorXakis/development you can see all your branches from **Your Branches** box on https://github.com/TorXakis/TorXakis/branches .

**Comment by pjljvandelaar** [comment]
How to make a recurring activity for this?
Regularly remove inactive branches....

**Comment by keremispirli** [comment]
Normally we remove every branch after we merge it. Some branches stick around though; in coveralls case I didn't delete it because I thought it will be useful in the future when it becomes applicable.
IMO as long as we keep deleting branches after we merge, we won't need to clean often.

**Comment by pjljvandelaar** [comment]
close issue: not relevant enough
