### ISSUE TITLE
Removing SortError

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#582]
The conclusion of our ( @pjljvandelaar , @capitanbatata , @keremispirli ) discussion is that even though SortError can be used in TorXakis models and be accepted by the parser, since SMT does not support it, most of the time it will eventually cause a TorXakis error. There are rare cases that it can legally exist in a TorXakis model, but we do not know anyone who makes use of such cases. As a result, it looks like removing SortError is better than supporting it.

@tretmans what's your opinion on this?

**Comment by tretmans** [comment]
I have no idea what this is about.

**Comment by pjljvandelaar** [comment]
You can write `ERROR` in a TorXakis model.
Yet often it doesn't work since we cannot pass `ERROR` on to the smt-solver.
We propose to remove the support for `ERROR`

**Comment by tretmans** [comment]
I see. Yes, then remove ERROR. Or there should be a way to prevent it from entering the SMT. In TXS itself and in evaluation it can be solved, I think.
But ANY has more or less the same problems. How is it done with ANY?

**Comment by pjljvandelaar** [comment]
Remove not only SortError but also Verror and Cerror (the objects with type SortError): handle errors via [Either](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Either.html). Use [partitionEithers](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Either.html#v:partitionEithers) to combine errors.
