### ISSUE TITLE
Cover test code in CodeClimate

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#584]
`test` folders are automatically excluded by CodeClimate: https://docs.codeclimate.com/docs/excluding-files-and-folders#section-auto-generated-file-and-folder-exclusions
We can add _"**/test"_ to our `codeclimate.yml` file to include them.

**Comment by capitanbatata** [comment]
Looks like a low-hanging fruit. Can't we do it in the `issue/565-newADTstructure` branch?

**Comment by keremispirli** [comment]
I wanted to see if everyone agrees :)

**Comment by keremispirli** [comment]
Done in #565
