### ISSUE TITLE
Hidden vars in BExpr for LPE

### ISSUE THREAD

**Issue by tretmans** [TorXakis/TorXakis#609]
In BehExprDefs.hs: add hidden variabelen in BExper voor LPE:

-- | ActOffer
-- Offer on multiple channels with constraints
data ActOffer = ActOffer
  { offers     :: Set.Set Offer      -- PvdL -- why not? -- Map ChanId [ChanOffer]
  , hidvars    :: Set.Set VarId
  , constraint :: VExpr
  } deriving (Eq, Ord, Read, Show, Generic, NFData, Data)

Heeft gevolgen van syntax (front) t/m Expand

**Comment by tretmans** [comment]
relates to #128

**Comment by pjljvandelaar** [comment]
Closed by #646
