### ISSUE TITLE
Investigate CNECTDEFS

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#614]
Identify how and where TorXakis communicates actions to&from SUT.

**Comment by keremispirli** [comment]
`cmdTester` and `cmdSimulator` in *TxsServer* call `txsSetTest` and `txsSetSim` in *TxsCore*, which has `putToW` (put to world) and `getFroW` arguments as types of `TxsDDefs.Action -> EnvCore.IOC TxsDDefs.Action` and `EnvCore.IOC TxsDDefs.Action` respectively.

TxsServer passes `putSocket` and `getSocket` functions from *SocketWorld* in **cnect** package, curried by `ioTime` and `deltaTime` parameters, and server state from *EnvServer*, to `TxsCore.txsSetTest` and `TxsCore.txsSetSim` functions.

In order to add support for communication over HTTP, we should implement a *HTTPWorld* which provides:

 - a function with signature `TxsDDefs.Action -> EnvCore.IOC TxsDDefs.Action` to be passed as *putToW*
 - a function with signature `EnvCore.IOC TxsDDefs.Action` to be passed as *getFroW*

and pass them to `TxsCore.txsSetTest` and `TxsCore.txsSetSim` functions in **txs-lib(?)**.

**Comment by capitanbatata** [comment]
I just saw my mention. I guess you know the answer after our pair programming session of yesterday, don't you?

**Comment by capitanbatata** [comment]
And maybe we can close this issue.
