### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#621]
When one parses the following (faulty) file:
[TorXakisWithEcho.txt](https://github.com/TorXakis/TorXakis/files/1852180/TorXakisWithEcho.txt)

One gets at the server:
```
Found configuration file at `.torxakis.yaml`.
61145

TXSSERVER >>  Starting  .....

TXSSERVER CMD >>  START
TXSSERVER RSP <<  MACK txsserver starting:  "NLYBSTQVP4NB77Y.code1.emi.philips.c
om" : 61145
TXSSERVER RSP <<  PACK START
TXSSERVER CMD >>  INIT examps\TorXakisWithEcho\TorXakisWithEcho.txs
TXSSERVER RSP <<  MACK
TXSSERVER RSP <<  MACK Parse Error:  txsserver: .stack-work\dist\67675594\build\
TxsHappy.hs:(3545,17)-(3629,17): Non-exhaustive patterns in case
```
and at torxakis
```
TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: "NLYBSTQVP4NB77Y.code1.emi.philips.com" : 61145
TXS >>
torxakis: <socket: 464>: hGetLine: does not exist (No such file or directory)
```

A clearer error message should be reported ;-(

**Comment by pjljvandelaar** [comment]
`front` is build using `ghc-options:         -Werror -Wall -O0 -optc-O3 -optc-ffast-math`.
Yet, why is this non-exhaustive pattern not reported during compilation?
`Wall` includes `warn-incomplete-patterns`....

**Comment by keremispirli** [comment]
Happy adds a `-w` flag to the generated TxsHappy.hs file, which suppresses **all** the warnings.
