### ISSUE TITLE
Is the comma in `LET` expressions needed. If so, what is an example of this?

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#628]
Let expressions allow to declare local variables separated by commas. For instance:

```text
LET a = e0, b = e1 IN e NI
```

The only difference in semantics wrt using semi-colons seems to be that an identifier defined the list of  `LET` declarations separated by comma's cannot be used at the defining expression side. For instance:

```text
FUNCDEF letParallel(x :: Int) :: Int ::=
     LET v = x, w = v IN
         w
     NI
ENDDEF
```

will give rise to an error, since the identifier "v" cannot be resolved. Are there cases in which this form of "parallel" evaluation is needed, and if so, could you give examples? Otherwise we're imposing an unnecessary cognitive burden in our users, and making things difficult for ourselves.

**Comment by pjljvandelaar** [comment]
Let sequential this using semicolon can be written als nested lets. And you know my opinion in expressing yourself in one way only.
Parallel/simultaneous let is useful when one want to change and use values.
For example,
Let list = cstr(n,list), n = n+1 in ...

**Comment by capitanbatata** [comment]
> Let sequential thus using semicolon can be written als nested lets

Did you mean let parallel?

> For example, Let list = cstr(n,list), n = n+1 in ...

Could you give a complete (minimal) model where this is useful? Or do we have any existing models? I thought that in `TorXakis` variables were not mutable, so there isn't anything like changing values.

**Comment by dnadales** [comment]
After discussing this with @tretmans we decided it is handier to keep both variants.
