### ISSUE TITLE
Add support for compiling all the behavior expressions

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#640]
The following language constructs have to be supported by `txs-compiler`:

- [x] Process instantiation
- [x] Parallel operators
- [x] Enable
- [x] Disable
- [x] Interrupt
- [x] Choice
- [x] Guard
- [x] Hide
- [x] Action prefix
- [x] Let expressions
- [x] Top level model definitions
- [x] Top level process definitions
- [x] Stop

**Comment by dnadales** [comment]
All behavior expressions are supported now, including tests for them.
