### ISSUE TITLE
Performance issues with v0.6.0

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#641]
I benchmarked v0.6.0 vs v0.5.0 twice; both results showed significant performance degradation in v0.6.0.

We should benchmark past commits to identify how this is introduced and solve it. Looking into significant pull requests can be a good starting point.

**Comment by pjljvandelaar** [comment]
Since the performance increase occurs in all use cases the root cause must be something general.
I assume the indirection / smart constructors that were added in `BExpr`.
If this is indeed the case, we should also inline the smart constructors of `ValExpr`.

**Comment by pjljvandelaar** [comment]
Btw. I propose not release an 0.6.1 version just for performance, we will have a new version in 3 months anyway.

**Comment by keremispirli** [comment]
Benchmarked commit a55243b3 (picked arbitrarily, being close to middle in the history), no performance degradation.
[Benchmarks_0.5.0-z3cvc4.xlsx](https://github.com/TorXakis/TorXakis/files/1897888/Benchmarks_0.5.0-z3cvc4.xlsx)

@pjljvandelaar In that case I'll benchmark following commits this evening:
d052bece | Issue/589 (#604) -> (smart constructors for BExpr)
c05f3fc7 | Parametrized Sut/Sim delta times (#600)

**Comment by pjljvandelaar** [comment]
Is this the solution?
```
-- see https://downloads.haskell.org/~ghc/7.0.2/docs/html/users_guide/pragmas.html for inlining differences of function definitions

stop :: BExpr
stop = BExpr Stop

actionPref :: ActOffer -> BExpr -> BExpr
actionPref = \a b -> BExpr (ActionPref a b)

guard :: VExpr -> BExpr -> BExpr
guard = \v b -> BExpr (Guard v b)

choice :: [BExpr] -> BExpr
choice = BExpr . Choice

parallel :: [ChanId] -> [BExpr] -> BExpr
parallel = \cs bs -> BExpr (Parallel cs bs)

enable :: BExpr -> [ChanOffer] -> BExpr -> BExpr
enable = \b1 cs b2 -> BExpr (Enable b1 cs b2)

disable :: BExpr -> BExpr -> BExpr
disable = \b1 b2 -> BExpr (Disable b1 b2)

interrupt :: BExpr -> BExpr -> BExpr
interrupt = \b1 b2 -> BExpr (Interrupt b1 b2)

procInst :: ProcId -> [ChanId] -> [VExpr] -> BExpr
procInst = \p cs vs -> BExpr (ProcInst p cs vs)

hide :: [ChanId] -> BExpr -> BExpr
hide = \cs b -> BExpr (Hide cs b)

valueEnv :: VEnv -> BExpr -> BExpr
valueEnv = \v b -> BExpr (ValueEnv v b)

stAut :: StatId -> VEnv -> [Trans] -> BExpr
stAut = \s v ts -> BExpr (StAut s v ts)
```

**Comment by pjljvandelaar** [comment]
Also the move to another compiler/LTS can cause such a general increase.
When was the haskell performance bug related to newtype https://ghc.haskell.org/trac/ghc/ticket/14936 introduced?
And what about https://ghc.haskell.org/trac/ghc/ticket/14964?

**Comment by keremispirli** [comment]
Both of these commits have the performance degradation:
d052bece | Issue/589 (#604) -> (smart constructors for BExpr) => [Benchmarks_0.5.0-BExp_issue589.xlsx](https://github.com/TorXakis/TorXakis/files/1901897/Benchmarks_0.5.0-BExp_issue589.xlsx)
c05f3fc7 | Parametrized Sut/Sim delta times (#600) => [Benchmarks_0.5.0-preBExp.xlsx](https://github.com/TorXakis/TorXakis/files/1901900/Benchmarks_0.5.0-preBExp.xlsx)

The results so far suggest that the degradation happened in one of these two commits:
c05f3fc7   | Parametrized Sut/Sim delta times (#600)
5c442d60 | Issue/582 remove sort error (#597)

I'll benchmark 5c442d60 this evening to find out. I'll also benchmark #647 to see if it improves the performance as much as #645 .

**Comment by keremispirli** [comment]
After yesterday's benchmarks, I believe the culprit is found:
c05f3fc7 | Parametrized Sut/Sim delta times (#600)
has low performance, while the previous commit:
5c442d60 | Issue/582 remove sort error (#597)
doesn't have the problem.

Checking the changes in c05f3fc7, I see 2 candidates:
1) Sim_deltaTime is changed from 200 to 2000
2) A delay of 5 seconds is added to sqatt, in order to write results to log files in case of error. (see #601)

I think no.2 is a good one to start with; also taking care of #601 along the way.

Btw #647 did not help with the performance; still has same degradation.

**Comment by pjljvandelaar** [comment]
@keremispirli is the 30 to 40% increase equal to a 5 second increase in all test cases?
In other words are we fouled by the representation?

**Comment by keremispirli** [comment]
Good point. I checked the numbers and the delay looks to be around 1s in most of the cases, 2.697s in `Hiding/match Int` and almost no change in `Hiding/hide second of sync second alternate`. So it doesn't look like to be because of those 5 seconds.

I'll run benchmarks now to see each one's impact.
