### ISSUE TITLE
TorXakis crashes when ANY is present in an expression

### ISSUE THREAD

**Issue by capitanbatata** [TorXakis/TorXakis#644]
The following function:

```text
FUNCDEF anyVal(x :: Int) :: Int ::=
    IF x == 0 THEN x ELSE ANY FI
ENDDEF
```

Will cause `TorXakis` to crash:

```text
txsserver: Illegal input constToSMT - Cany {sort = SortId {name = "Int", unid = 102}}
CallStack (from HasCallStack):
  error, called at src/TXS2SMT.hs:196:18 in solve-0.2.2.0-IvrvCS7YwKQ6EeQTTjovFZ:TXS2SMT
```

What is the expected behavior here? Should the function above compile at all?

**Comment by pjljvandelaar** [comment]
`ANY` may never be evaluated.
`ANY` is the `Nothing` of a `Maybe Value` where we assume a value will be present when needed.
It is to allow for uninitialized variables in StautDefs and ProcDefs generated by Carsten.

**Comment by pjljvandelaar** [comment]
I propose to close this issue
@damian do you agree?

**Comment by capitanbatata** [comment]
> ANY is the Nothing of a Maybe Value 
Well, I wouldn't expect a Haskell program to crash for using `Nothing` ;) 

>  It is to allow for uninitialized variables in StautDefs and ProcDefs generated by Carsten.
But shouldn't the compiler restrict the uses of ANY then?

> I propose to close this issue @damian do you agree?

Well, problem is that the current compiler allows `ANY`'s anywhere (no pun intended), and then `TorXakis` just crashes. I'd say that to close this issue we have to either be precise about the places in which any is allowed, or be robust when these errors occur (which might be confusing for users).

**Comment by pjljvandelaar** [comment]
I think the rule is
ANY is only allowed in procInst as an argument.

**Comment by capitanbatata** [comment]
Then shouldn't the compiler forbid other uses of `ANY`? In that case we should implement that (either in the new compiler or in the old...)

**Comment by pjljvandelaar** [comment]
We might even forbid `ANY` in the compiler...
`ANY` is only used in internal model 2 model transformations.
The code generated by Carsten is than no longer parsable, yet that is not the intention anyway:
the translation to LPE is fast enough to do it every time when a file is parsed.

**Comment by capitanbatata** [comment]
> We might even forbid ANY in the compiler...

Sounds like music to my ears. Now the question is why did I spend time translating ANY to the new compiler :/ ...

**Comment by pjljvandelaar** [comment]
The root cause is two fold.
1. We don't support Generics/Templates (see #410) yet.
If #410 was supported, we would never have opted for `ANY`.
We would have chosen the `Maybe T` with `Nothing` and `Just x::T` as two constructors.
2. We don't document enough & we don't restrict enough. If we would have you might have read that it is not allowed by the compiler or only in procInst.

**Comment by dnadales** [comment]
Let's implement this restriction in the new compiler (after discussing with @tretmans and @pjljvandelaar),

**Comment by dnadales** [comment]
Ok, just to double check: @tretmans and @pjljvandelaar, we have the following integration test:

```text
CHANDEF Chandefs ::=
    A, X :: Int
ENDDEF

PROCDEF p0 [A, X::Int] (n, m::Int) ::=
    A ? m >-> p1 [A,X] (n, m)
ENDDEF

PROCDEF p1 [A,X::Int] (n, m::Int) ::=
    X ! n + m >-> p0 [A, X] (n, ANY)
ENDDEF

MODELDEF Mod ::=
    CHAN IN A
    CHAN OUT X
    BEHAVIOUR p0 [A, X] (2, ANY)
ENDDEF
```
As the preceding discussion concluded, we **won't** support the use of `ANY` in the new compiler, so this test must be removed. Is that correct?

**Comment by pjljvandelaar** [comment]
Fine with me.
