### ISSUE TITLE
nightly build fails: disk full

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#655]
Tonight's build failed:
```
Log files have been written to: /home/runner/TorXakis/.semaphore-cache/.stack-work/logs/
/home/runner/TorXakis/.semaphore-cache/.stack/snapshots/x86_64-linux/lts-11.5/8.2.2/doc/template-haskell-2.12.0.0/.copyFile4244974172016264854.tmp: copyFile:atomicCopyFileContents:withReplacementFile:copyFileToHandle:copyData:hPutBuf: resource exhausted (No space left on device)
```

see https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/327 for more details

**Comment by pjljvandelaar** [comment]
And again:
```
Progress: 41/43               /usr/bin/ld.gold: fatal error: .semaphore-cache/test/.stack_work/dist/x86_64-linux/Cabal-2.0.1.0/build/models-test/models-test: No space left on device
```
See also
https://semaphoreci.com/capitanbatata/torxakis/branches/issue-589_choice/builds/3

**Comment by keremispirli** [comment]
`.stack-work` folder grows with every lts upgrade. I removed it to clear some space; let's see if it helps.

**Comment by pjljvandelaar** [comment]
Problem doesn't seem solved:
```
ghc-pkg: /home/runner/TorXakis/.semaphore-cache/.stack/snapshots/x86_64-linux/lts-11.5/8.2.2/pkgdb/package.cache23874-1.tmp: hPutBuf: resource exhausted (No space left on device)
```
See https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/329

**Comment by keremispirli** [comment]
looks like `.stack` folder also has a lot of old stuff:

`Reading package info from "/home/runner/TorXakis/.semaphore-cache/.stack/snapshots/x86_64-linux/lts-10.0/8.2.2/pkgdb/Only-0.1-K3HSyq2koL8JtFXn0ZkrT6.conf" ... done.`

gonna remove that, too.

**Comment by keremispirli** [comment]
Looks like the caches grew big indeed:
```
Size of /home/runner/TorXakis/.semaphore-cache/.stack-work:
1.1G	/home/runner/TorXakis/.semaphore-cache/.stack-work
rm -rf /home/runner/TorXakis/.semaphore-cache/.stack-work
Done
Size of /home/runner/TorXakis/.semaphore-cache/.stack:
5.9G	/home/runner/TorXakis/.semaphore-cache/.stack
rm -rf /home/runner/TorXakis/.semaphore-cache/.stack
Done
```

But despite many successful builds like this, we still get same cache when I start a new build.  I wrote to SemaphoreCI about this; waiting response from their support.

**Comment by keremispirli** [comment]
If you're an admin in the project, you can see an "Expire Dependency Cache" button which clears the cache.

It works.
