### ISSUE TITLE
nightly build fails: cvc4 not found

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#658]
SemaphoreCI reports
```
cvc4 not found in cache or different version than 20180306
rm: cannot remove ‘/home/runner/TorXakis/.semaphore-cache/bin/cvc4*’: No such file or directory
```
See https://semaphoreci.com/capitanbatata/torxakis/branches/develop/builds/331

related to #655 too much removed?

**Comment by dnadales** [comment]
Cache deletion shouldn't cause the builds to fail. @keremispirli could you change the `rm` command to use the `-f` flag so that the exit code will be zero?
