### ISSUE TITLE
A behavior expression with an undefined variable causes TorXakis to crash

### ISSUE THREAD

**Issue by dnadales** [TorXakis/TorXakis#666]
The following process:

```text
PROCDEF enabler[X :: Int]() ::=
    X ? v >-> EXIT ! 10 ! v >>> ACCEPT ? a ? b :: Int IN X ! a + bb NI
ENDDEF
```
which contains an undefined variable `bb` will cause `TorXakis` to crash:

```text
TXS >>  TXS0422: Operator not resolved: '"+"'
TXS >>  Argument 0: ValExpr {view = Vvar (VarId {name = "a", unid = 1051, varsort = SortId {name = "Int", unid = 102}})}
```

furthermore, the error message is misleading, and it does not even mention the offending symbol (`bb`).

**Comment by pjljvandelaar** [comment]
Not a crash, just a bad error message in my opinion.

**Comment by dnadales** [comment]
Nope. It actually crashes.

**Comment by pjljvandelaar** [comment]
Ok it crashes before Argument 1 is described....
