### ISSUE TITLE
Shouldn't we remove all linux commands from semaphore CI configuration?

### ISSUE THREAD

**Issue by dnadales** [TorXakis/TorXakis#681]
And instead put them in scripts. Otherwise:
  - Things are defined at two places.
  - Semaphore CI is not versioned

For instance the $PATH variable could be set in a script

![screenshot from 2018-05-08 13-11-13](https://user-images.githubusercontent.com/175315/39754173-9712040e-52c1-11e8-8678-094018a1879f.png)

Does it make sense to put the exports as part of `setup.sh`?

**Comment by keremispirli** [comment]
The reason for writing `export`s as separate commands was that they don't work when they are in a script. The exported variables were only available within the script, not for following scripts.

If that behaviour is changed, then we should put them back into relevant scripts.

**Comment by dnadales** [comment]
Ok, clear.
