### ISSUE TITLE
bug in eqProcDefs (LPEfunc.hs)

### ISSUE THREAD

**Issue by CarstenRuetz** [TorXakis/TorXakis#682]
Comparison operator for two ProcDefs (maps) gives wrong result:

```
procDefs' = Map.fromList [(ProcId {ProcId.name = (T.pack "P"), 
                                    ProcId.unid = 111, 
                                    ProcId.procchans = [], 
                                    ProcId.procvars = [], 
                                    ProcId.procexit = NoExit},
                            (ProcDef [] [] stop))]

eqProcDefs procDefs' (Map.empty)
```

**Expected result**
False

**Observed result**
True

**Reason**
Implementation zips the lists of the two maps. In case of unequal length of those lists, the shortest one is cutting the other list short. Hence, the comparison yields an unintended result.

**Original implementation**
```
eqProcDefs :: ProcDefs -> ProcDefs -> Bool
eqProcDefs procDefsL procDefsR =
    let l = Map.toList procDefsL
        r = Map.toList procDefsR
        zipped = zip l r
        compared = map comp zipped in
    and compared
    where
      comp (l,r) = eq_elem l r
      eq_elem (procIdL, procDefL) (procIdR, procDefR) =
        reset procIdL == reset procIdR && eqProcDef' procDefL procDefR`
```

**Suggested fix**
Compare the length of the two lists for equality

```
eqProcDefs :: ProcDefs -> ProcDefs -> Bool
eqProcDefs procDefsL procDefsR =
    let l = Map.toList procDefsL
        r = Map.toList procDefsR
        zipped = zip l r
        compared = map comp zipped in
    and compared && length l == length r
    where
      comp (l,r) = eq_elem l r
      eq_elem (procIdL, procDefL) (procIdR, procDefR) =
        reset procIdL == reset procIdR && eqProcDef' procDefL procDefR
```

Applied the fix in the LPE branch already. Suggest to do the same in development. Opinions?

**Comment by CarstenRuetz** [comment]
I think it's used in the LPE part only, anyway?!

**Comment by dnadales** [comment]
The fix makes sense. I would change `compared && length l == length r` to `length l == length r && compared` so that the function can exit earlier when the lengths differ.

Is there any other kind of input expected from me?

**Comment by CarstenRuetz** [comment]
sounds good. no further input needed.

**Comment by pjljvandelaar** [comment]
I assume when your LPE branch is merged with develop, this bug is also solved in develop.

Note: for performance reasons it might be better to make your own zip & compare function instead of using length and compare where
```
zipcompare [] [] = true
zipcompare a [] = false
zipcompare [] a = false
zipcompare (x:xs) (y:ys) = compare (x,y) && zipcompare xs ys
```
