### ISSUE TITLE
Missing specifications for SUT connection (string encoding, new line format)

### ISSUE THREAD

**Issue by tacopetri** [TorXakis/TorXakis#719]
Hi,

I'm currently building an adapter on Windows, for a C# app. Using the 0.6.0 release version.

Two important details seem to be missing from the wiki and the examples:
https://github.com/TorXakis/TorXakis/wiki/CnectDefs

- Socket streams must have UTF-8 string encoding, without BOM. Using the C# default (with BOM), gives an unhelpful error:
torxakis.exe: <socket: 672>: hGetLine: invalid argument (Bad file descriptor)

- The new line format must be Linux (\n). When using the Windows style (\r\n) the \r is considered part of the output string. Pretty standard, but good to mention nonetheless.

I haven't encountered any other platform-specific issues so far. =)

**Comment by pjljvandelaar** [comment]
Thanks for the feedback.
I have added your remarks to the wiki. See at the end of the page of https://github.com/TorXakis/TorXakis/wiki/CnectDefs
