### ISSUE TITLE
Refactor the new compiler

### ISSUE THREAD

**Issue by dnadales** [TorXakis/TorXakis#724]
Everything should be simplified to the extent possible.

The mock ups for the simplified functions have the `_2` suffix (to make them searchable).

- [x] Minimize the maps that are passed to `expDeclToValExpr`
- [x] Write a function that merges `Map (Loc VarRefE) (Either (Loc VarDeclE) [Loc FuncDeclE])`, `Map (Loc VarDeclE) VarId`, and Map `(Loc FuncDeclE) (Signature, Handler VarId)` into `Map (Loc VarRefE) (Either VarId [(Signature, Handler VarId)])`. **WARNING** this requires that a variable declaration has also a `Loc VarRefE` and that this is also in the map! (see the code for `expDeclToValExpr`).
- [x] Find a **single** place to replace `expDeclToValExpr` by `expDeclToValExpr_2` (this requires to use the map merging function defined above).
- [x]  Assuming everything (tests and end-to-end tests) works, find another place to replace  `expDeclToValExpr` by `expDeclToValExpr_2`. Test. Repeat.
- [x] Assuming everything (tests and end-to-end tests) works, rename `expDeclToValExpr_2` to `expDeclToValExpr` (removing the old version).
- [x] See whether you can simplify the constraints of `inferExpTypes` from `MapsTo Text SortId mm
                 , MapsTo (Loc VarDeclE) SortId mm
                 , MapsTo (Loc FuncDeclE) Signature mm
                 , MapsTo (Loc VarRefE) (Either (Loc VarDeclE) [Loc FuncDeclE]) mm ` to two parameters `Map (Loc VarRefE) (Either VarId [(Signature, Handler VarId)])` and `Map (Loc VarDeclE) SortId`.
  - **We can't!** the reason is that `inferExpTypes` will create new entries `(Loc VarDeclE, SortId)`, so loosing information of the associations between `Loc VarRefE` and `Loc VarDeclE` can potentially break the type inference algorithm.
- [x] Simplify the constraints of `offerSid`
- [x] Simplify the constraints of `toOffer`
- [x] Simplify all the constraints in `BehExprDefs`.
- [x] See if you can **globaly** determine the maps that are required by `expDeclToValExpr`.  **WARNING**  (yes, again!) this requires that a variable declaration has also a `Loc VarRefE` and that this is also in the map! (see the code for `expDeclToValExpr`).
  - **Cancelled**: this is too risky at this stage. We'll focus on delivering what we have now.
- [x] Minimize the maps that are passed to `toBExpr`.
  - **Cancelled**, see above.
- [x] Finish the implementation of `procDeclsToProcDefMap_2`
   - **Cancelled**, see above.
- [x] Consider replacing `MapsTo` by just passing functions. This solution is too ackward.
  - **Cancelled**: while the solution might be awkward, it is also elegant, and helps a lot in reducing boilerplate. Better alternatives require more time, which we don't have at the moment.

**Comment by pjljvandelaar** [comment]
@capitanbatata All items have been checked.
Can this issue be closed? If so, please close!
