### ISSUE TITLE
"unexpected type of bexpr" error for LuckyPeople

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#734]
When I load Lucky People model and run `lpe Model`, I get this error. It's thrown from `sys/lpe/src/LPE.hs` L186:

``` haskell
preGNFBExpr _ _ _ _ _ _ =
    error "unexpected type of bexpr"
```

**Comment by pjljvandelaar** [comment]
Probably due to guard which is not yet implemented

**Comment by CarstenRuetz** [comment]
The ProcDef luckyPeople includes indeed guards thus is not yet translatable. 

Was just going to test it though - since I'm working on the guard translation. But got stuck on a compile error. Going to post an issue.

**Comment by CarstenRuetz** [comment]
compile error fixed. Going to work on this asap.

**Comment by CarstenRuetz** [comment]
Just discovered that LuckyPeople shows a case of guards that I didn't consider previously. Going to change the LPE translation accordingly, then I'll get back to this.

**Comment by CarstenRuetz** [comment]
done. 
Guard is fully implemented, all issues with LuckyPeople resolved. See latest commit in branch lpe.
