### ISSUE TITLE
ProcId contains information which is not part of the process' signature

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#746]
The `ProcId` is a reference to the `ProcDef`.
A `ProcId` should only contain information related to the `ProcDef`s signature.
However, `ProcId` is currently defined as follows
```
data ProcId         = ProcId    { name      :: Name
                                , unid      :: Id
                                , procchans :: [ChanId]
                                , procvars  :: [VarId]
                                , procexit  :: ExitSort
                                }
     deriving (Eq, Ord, Read, Show, Generic, NFData, Data)
```
Hence it also contains the names of the channels and  the variables.

It should be changed to:
```
data ProcId         = ProcId    { name      :: Name
                                , unid      :: Id
                                , procchans :: [ChanSort]
                                , procvars  :: [SortId]
                                , procexit  :: ExitSort
                                }
     deriving (Eq, Ord, Read, Show, Generic, NFData, Data)
```
where
```
newtype ChanSort = ChanSort [SortId]
     deriving (Eq, Ord, Read, Show, Generic, NFData, Data)
instance Resettable ChanSort
instance Identifiable ChanSort
```

Unfortunately, some parts of the code use the names. For example, in LPE.hs in the function `stepsUpdateProcInsts` on line 829 `chansInst` is defined using `procId`.
Is it possible to add an additional parameter and pass `chansDef` on line 744?

I can make most changes, however in LPE I might need some support.

**Comment by pjljvandelaar** [comment]
@CarstenRuetz please look at branch issue746/ProcId
(https://github.com/TorXakis/TorXakis/tree/issue746/ProcId)

It seems that you have used the channels of the procId to detect channel switching.
Now that the chanId only contain type this check fails (of course).
Yet, I am unable to localize the piece of code responsible. Please help!
Every thing build and all tests succceed except for two LPE tests....

**Comment by CarstenRuetz** [comment]
Yes, I indeed used the channels of the procId.
Should be changeable like you said.

However, I get no failing tests in the current state of branch issue746/ProcId:
Cases: 91  Tried: 91  Errors: 0  Failures: 0

Did you commit the changes to the ProcId definition already? Then I can have a look at it. There might be other places where I used information from the ProcId definition that you want to remove.

**Comment by pjljvandelaar** [comment]
I was surprise by your remark.
So I duplicated the experiment at my other working location
and indeed I forgot to check in some of my changes....
Sorry ;-(

Will update the branch tomorrow when I am at ESI once more. 

P.S. I got
```
Cases: 79  Tried: 79  Errors: 0  Failures: 0
```

**Comment by pjljvandelaar** [comment]
strange, back at the original work spot:
```
On branch issue746/ProcId
Your branch is up to date with 'origin/issue746/ProcId'.
```
And https://github.com/TorXakis/TorXakis/blob/issue746/ProcId/sys/bexpr/src/ProcId.hs really contains the changes....

```
### Failure in: 2:LPE:9:ProcDef Identity
test\TestLPE.hs:435
ProcDef identity
### Failure in: 2:LPE:11:switching channels
test\TestLPE.hs:597
switching channels
Cases: 79  Tried: 79  Errors: 0  Failures: 2
```

**Comment by pjljvandelaar** [comment]
line 830: 
`stepsUpdateProcInsts procs procToParams pcMap procIdNew _ (TxsDefs.view -> ActionPref actOffer procInst''@(TxsDefs.view -> ProcInst procIdInst' chansInst _paramsInst)) =`
seems to be relevant: changing `_` to `chansInst` and vice versa results in other error in the same test.
Yet, I expected that the two arguments should have the same value (but maybe I am wrong ;-)

**Comment by pjljvandelaar** [comment]
Will look tomorrow at other work spot once more what I (and maybe you) did wrong, since everything is correctly checked in....

**Comment by pjljvandelaar** [comment]
When I executed a `git pull` today I got
```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> issue746/ProcId
```
This challenged my view on my `issue746/ProcId` branch: maybe I did not get it from the archive at this work spot!
Maybe I executed ` git checkout -b issue746/ProcId` instead of ` git checkout issue746/ProcId`!!

So, I deleted the branch  (after `git checkout develop`) by `git branch -D issue746/ProcId`.
Executed ` git checkout issue746/ProcId` and now I got the desired and expected output of `stack test lpe`:
```
### Failure in: 2:LPE:9:ProcDef Identity
test\TestLPE.hs:435
ProcDef identity
### Failure in: 2:LPE:11:switching channels
test\TestLPE.hs:597
switching channels
Cases: 79  Tried: 79  Errors: 0  Failures: 2
```
@CarstenRuetz Did you make the same mistake as I did????

**Comment by CarstenRuetz** [comment]
solved.

You almost got there, chained the right chansDef through.
Just in the last case of stepsUpdateProcInsts you used the channels of the original ProcInst (that is to be substituted here) instead of the chained-through channels.

Took some debugging, but it's done :)
See the latest commit.

**Comment by pjljvandelaar** [comment]
@CarstenRuetz can we merge the latest lpe commit with the main branch?

**Comment by pjljvandelaar** [comment]
I have to check that all software on top of lpe is also fine...
LPE was not the only part that needed changes ;-)

**Comment by CarstenRuetz** [comment]
Yes, I actually merged the develop branch of today into lpe already. So this should be quick for you.
