### ISSUE TITLE
Compiler crashes when using constants as function arguments

### ISSUE THREAD

**Issue by ramon-janssen** [TorXakis/TorXakis#777]
The new compiler gives an error when supplying CONSTDEF-arguments to function calls:
```
CONSTDEF zero :: Int ::= 0 ENDDEF
FUNCDEF id1(x :: Int) :: Int ::= x ENDDEF
FUNCDEF id2(x :: Int) :: Int ::= 
    id1(zero) + x
ENDDEF
```
This lets txsserver crash with the following error:
`txsserver: FuncId FuncId {name = "zero", unid = 1046, funcargs = [], funcsort = SortId {name = "Int", unid = 102}} not found in mapping with keys: [FuncId {name = "id1", unid = 1044, funcargs = [SortId {name = "Int", unid = 102}], funcsort = SortId {name = "Int", unid = 102}},FuncId {name = "id2", unid = 1045, funcargs = [SortId {name = "Int", unid = 102}], funcsort = SortId {name = "Int", unid = 102}}]`

Workaround: use a 0-ary FUNCDEF instead of a CONSTDEF.

**Comment by pjljvandelaar** [comment]
Zero is not part of the defined functions (it is optimized away). Zero should be in the signatures. So either zero is not inserted into the signatures or defined functions is used instead of signatures.

**Comment by pjljvandelaar** [comment]
The error message seems to be originated from TXS2SMT.hs
So it seems `zero` is added to functions yet has no implementation...
Which is desired since it just a substitution that can be performed once!

**Comment by pjljvandelaar** [comment]
@dnadales any idea why `zero` is not added?

**Comment by dnadales** [comment]
From the top of my head I have no idea. I'm a bit busy with ramping up in
my new job, so I cannot guarantee I'll have time to look a this in the near
future. Sorry.
