### ISSUE TITLE
Migrate AcceptanceTest.bat

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/TorXakis#78]
First 3 steps are in test/Makefile

**Comment by pjljvandelaar** [comment]
Didn't we already achive this?

**Comment by keremispirli** [comment]
We only need to run testCopyright. It should be part of build script rather than example tests. I'll take care of it.

**Comment by keremispirli** [comment]
- [ ] Add testCopyright ot build script
- [ ] Remove migrated files
