### ISSUE TITLE
Starting TorXakis: welcome message sent over error channel, not output channel?

### ISSUE THREAD

**Issue by tacopetri** [TorXakis/TorXakis#791]
Hi!

I am catching both the output and error messages coming from TorXakis during a test run. For logging purposes and to display them inside the console window of the app being tested.

Is it my implementation, or is the welcome message "TorXakis :: Model-Based Testing" sent over the ERROR channel, not the OUTPUT channel as expected?

![torxakis startup error channel](https://user-images.githubusercontent.com/37344555/46299338-6cc42300-c5a1-11e8-838e-909b89f6869a.png)

(using the 0.7.0 release)

**Comment by pjljvandelaar** [comment]
As can be seen on
https://github.com/TorXakis/TorXakis/blob/develop/sys/ui/src/UI.hs#L65
and
https://github.com/TorXakis/TorXakis/blob/develop/sys/ui/src/UI.hs#L82
Both the welcome and farewell message are sent over the error channel (stderr).

@tretmans is this a bug or a feature?
When it is a feature, please inform us why!

**Comment by pjljvandelaar** [comment]
Also in TxsServer stderr is used for echoing commands. Why?

**Comment by pjljvandelaar** [comment]
I assumed it was an error: use stdout at those four locations instead!
