### ISSUE TITLE
Intermittent error: <socket: 652>: hGetLine: invalid argument (Bad file descriptor)

### ISSUE THREAD

**Issue by tacopetri** [TorXakis/TorXakis#792]
Hi!

As the title suggest I am getting intermittent errors that halt a test run completely.
(using the 0.7.0 release)

Could someone please tell me what this error means, and whether it's my fault? =)
<socket: 652>: hGetLine: invalid argument (Bad file descriptor)

It looks like TorXakis doesn't like/understand some output that my adapter is sending. But the error is not consistent, and I'm only sending output that is defined in the test model. Most of the time I can complete a test run (which loops through the model 2 times) without problems.

I am combining INPUT and OUPUT over a single TCP connection, if that matters:

CNECTDEF System ::=
 CLIENTSOCK
  CHAN OUT Sync1 HOST "localhost" PORT 8001
  ENCODE Sync1 ? s -> ! toString(s)
  
  CHAN OUT Sync2 HOST "localhost" PORT 8002
  ENCODE Sync2 ? s -> ! toString(s)
 
  CHAN OUT Input HOST "localhost" PORT 2345
  ENCODE Input ? s -> ! toString(s)

  CHAN IN Output HOST "localhost" PORT 2345
  DECODE Output ! fromString(s) <- ? s
ENDDEF

**Comment by tacopetri** [comment]
I'm attaching my full test model, in case that helps.

torxakis ReferenceSynchronized.txs
stepper Model
step 110

[ReferenceSynchronized.txt](https://github.com/TorXakis/TorXakis/files/2434769/ReferenceSynchronized.txt)

(NOTE: I cannot attach .txs files, so I renamed it to .txt)

**Comment by tacopetri** [comment]
I am also getting a slightly different error sometimes (note the line number, 656 not 652):

<socket: 656>: hGetLine: invalid argument (Bad file descriptor)

**Comment by pjljvandelaar** [comment]
What is your platform?
I tried it on windows and I could not reproduce it.
How often does it occur? once every 10 times, 100 times, 1000 times?

**Comment by pjljvandelaar** [comment]
I got to reproduce it (with yet another number):
`torxakis.exe: <socket: 508>: hGetLine: does not exist (No such file or directory)`
by just `step 1000000`

**Comment by tacopetri** [comment]
I am running on Windows 10 Pro.

It occurs relatively often, once every 10 times maybe. It seems to happen more frequently during the first fresh test run of the day: I reproduced it on the first try today for example.

Also got a different line again:
`torxakis.exe: <socket: 660>: hGetLine: invalid argument (Bad file descriptor)`

**Comment by pjljvandelaar** [comment]
By starting `txsserver` and `torxakis` separately, I get the following error message
```
txsserver.exe: Error in model: Accessing field with number 0 of constructor CstrId {name = "CreateItemEnd", unid = 1003,
 cstrargs = [SortId {name = "Int", unid = 102}], cstrsort = SortId {name = "Internal", unid = 1000}} on value from const
ructor CstrId {name = "CreateItemBegin", unid = 1002, cstrargs = [SortId {name = "Int", unid = 102}], cstrsort = SortId
{name = "Internal", unid = 1000}}
CallStack (from HasCallStack):
  error, called at src\ValExprImpls.hs:142:14 in valexpr-0.0.1.0-65hRvUHlZ9zHkjGtrdhQyN:ValExprImpls
```
so problem is in the model.

An indeed it is: one should use ITE. See https://github.com/TorXakis/TorXakis/wiki/IteValExpr

TorXakis has no order, so the isX(x) doesn't enforce that after the /\ only checks with datatypes constructed by X are used.

So change to 
```
 Sync2 ? begin1 :: Internal [[ IF isCreateItemBegin(begin1) THEN createItemBeginId(begin1) == 3 ELSE False FI ]]
```
and the errors should be gone!

**Comment by tacopetri** [comment]
Many thanks, I'll fix my model! =)

Are there plans to pass these txsserver errors to torxakis in the future? It would really help if the error messages weren't so cryptic on the client side.

**Comment by pjljvandelaar** [comment]
We are in the middle of a big refactor (see branch refactor/All).
However, I get squeezed by other project activities....

**Comment by pjljvandelaar** [comment]
@tacopetri please close the issue when you are able to run your model for thousands of steps without ever crashing.

**Comment by tacopetri** [comment]
I ran the stepper for 10.000 steps without errors. I also ran the tester against the SUT for 5000 steps without errors. Closing issue!

====

These replacements seem to have worked:

`Sync ? begin :: Internal [[ IF isCreateItemBegin(begin)
                              THEN createItemBeginId(begin) == 1
                              ELSE False FI ]]`

`Input ? connect1 :: External [[ IF isConnectItem(connect1)
                                 THEN (connectItemId1(connect1) == 1)
                                 /\ (connectItemId2(connect1) == 2)
                                 ELSE False FI ]]`

**Comment by pjljvandelaar** [comment]
Great!

Maybe I should give more attention to the remark about accessors functions:

_Note that these accessor functions are only defined for instances of the Cstr_Int constructor, i.e.,
instances of List_Int for which isCstr_Int(x) returns True. head(CNil_Int) and tail(CNil_Int) are thus not defined.
One should guard the usage of accessor functions with the constructor check, using IF THEN ELSE FI ._
```
IF isCstr_Int(x) THEN head(x) == 5 ELSE False FI
```
on page https://github.com/TorXakis/TorXakis/wiki/Function

**Comment by tacopetri** [comment]
The function page seems pretty clear to me.

However, that the order of evaluation is not guaranteed when combining functions (leading to seemingly random errors), is a bit sneaky.

If I understand correctly, under *some* circumstances the expression:
`isCstr_Int(x) /\ (head(x) == 1)`
Is re-ordered/optimized internally to:
`(head(x) == 1) /\ isCstr_Int(x)`
Leading to a hard error since the `head` function is not defined for all possible types of x.

An example showcasing the combination of TYPEDEF functions and `/\ \/` (and its pitfalls) would certainly be helpful for beginners. =)
