### ISSUE TITLE
Windows MSI Installer - Defaults to Program Files (x86) not Program Files

### ISSUE THREAD

**Issue by tacopetri** [TorXakis/TorXakis#798]
Hi,

TorXakis runs as 64 bit on my machine, is there even a scenario where it runs as 32 bit?

The MSI installer has this as installation folder:
`C:\Program Files (x86)\TorXakis`
while it should really be:
`C:\Program Files\TorXakis`

Tested with the 0.7.0 release installer.

**Comment by pjljvandelaar** [comment]
I guess this is legacy: TorXakis used to be 32 bits. Will pick it up for the next release, #761.

**Comment by pjljvandelaar** [comment]
Also z3 and cvc4 were 32 bits. Have to check them as well.

**Comment by tacopetri** [comment]
It always feels nice to eliminate the legacy 32 bit components of a software system. =)

**Comment by pjljvandelaar** [comment]
Is issue of windows installer so closed in the general TorXakis project.

**Comment by pjljvandelaar** [comment]
Done correctly: See https://www.howtogeek.com/129178/why-does-64-bit-windows-need-a-separate-program-files-x86-folder/
```
On 64-bit versions of Windows, 64-bit applications install to the Program Files folder. However, 64-bit versions of Windows also support 32-bit programs, and Microsoft doesn’t want 32-bit and 64-bit software getting mixed up in the same place. So, 32-bit programs get installed to the “C:\Program Files (x86)” folder, instead.
```
