### ISSUE TITLE
Torxakis v0.7 not working for Ubuntu 16.04

### ISSUE THREAD

**Issue by alanrandrade** [TorXakis/TorXakis#821]
After installing Torxakis 0.7 using the .deb file in Ubuntu 16.04, an error message is given when using the tool (see attachment).

My colleague, who is trying to use it did some research and it seems not to be a good idea to update GLIB. The solution for him was to use Ubuntu 18.04. However, I do have 0.7 in my Ubuntu 16.04, which I built from source, maybe there is something wrong with the .deb file?

Regards.

![screenshot from 2018-11-29 13-09-46](https://user-images.githubusercontent.com/14285658/49221275-f1cc8c80-f3d8-11e8-91a9-0136ea5b4f0b.png)
![screenshot from 2018-11-29 13-13-54](https://user-images.githubusercontent.com/14285658/49221284-fabd5e00-f3d8-11e8-81f2-bdbd9b148a13.png)

**Comment by pjljvandelaar** [comment]
With the 0.8.0 release planned for this month. I propose to look into it, yet fix it only for 0.8.0 and no longer for 0.7.0.

**Comment by dnadales** [comment]
Thanks for reporting this @alanrandrade. I'm looking into this, but it might take a while till I have enough time to solve it.

I'm trying to build `.deb` package from an Ubuntu 16.04 docker container  to see if this will solve the problem. I'll keep you posted.
