### ISSUE TITLE
Invalid ControlLoopModel model after LPE transformation

### ISSUE THREAD

**Issue by ikbendedjurre** [TorXakis/TorXakis#846]
Applying the `lpe` command to `examps/ControlLoop/ControlLoopModel.txs` does not work because one of the processes contains a parallel loop (`found Parallel loop with ProcId measure`). So this is correct.

In order to work with the file, I changed the `|||` operator on line 61 to `>->`.

Afterwards, the output model of `lpe` is invalid: several summands use 35 expressions as parameter values in their process instantiation, but the process requires 34, and one of the parameter values is `nextId`, which is a variable that is out-of-scope. Maybe this parameter value was supposed to be removed?

**Comment by pjljvandelaar** [comment]
It seems that solving #853 also solved this issue.
I hope #853 will be merged into the development branch today.
@ikbendedjurre can you confirm this?
If so, please close this issue.

**Comment by pjljvandelaar** [comment]
The lpe model is attached (too long to include)
and it runs perfect in sync (see ModelBoth at the bottom).

[DjurreControlLoopModel.lpe.txt](https://github.com/TorXakis/TorXakis/files/2764213/DjurreControlLoopModel.lpe.txt)

@ikbendedjurre can mCrl2 proof they are equivalent?

**Comment by ikbendedjurre** [comment]
> It seems that solving #853 also solved this issue.
> I hope #853 will be merged into the development branch today.
> @ikbendedjurre can you confirm this?
> If so, please close this issue.

Confirmed.

**Comment by ikbendedjurre** [comment]
> The lpe model is attached (too long to include)
> and it runs perfect in sync (see ModelBoth at the bottom).
> 
> [DjurreControlLoopModel.lpe.txt](https://github.com/TorXakis/TorXakis/files/2764213/DjurreControlLoopModel.lpe.txt)
> 
> @ikbendedjurre can mCrl2 proof they are equivalent?

I simplified the data structure of the model (changing Ints to a 3-value struct) before feeding it to mCRL2. Afterwards, the state spaces of lpe(P) and lpe(lpe(P) || P) are only weakly bisimilar; strong bisimulation does not hold for some reason (different from what I would expect, maybe LPE transform does not preserve invisible steps?).

**Comment by pjljvandelaar** [comment]
@tretmans Any ideas?
