### ISSUE TITLE
Channel type not checked

### ISSUE THREAD

**Issue by ikbendedjurre** [TorXakis/TorXakis#864]
Recently, a trick was added to export LPE models with hidden variables to text: a temporary channel is added that is immediately hidden, such as in the example below:

```
PROCDEF p [ A ] ( y :: Int ) ::=
    HIDE [ HiddenChannel ] IN A | HiddenChannel ? x :: Int [[ x > 0 ]] >-> p [ A ] ( y + x ) NI
ENDDEF

CHANDEF Chans ::=
    X
ENDDEF

MODELDEF Model ::=
    CHAN IN
    CHAN OUT X
    BEHAVIOUR p [ X ] ( 0 )
ENDDEF
```

But when I run the stepper for the example, I get

```
CallStack (from HasCallStack):
  error, called at src\ValExprImpls.hs:484:54 in valexpr-0.0.1.0-65hRvUHlZ9zHkjGtrdhQyN:ValExprImpls
CallStack (from -prof):
  ValExprImpls.compSubst' (src\ValExprImpls.hs:(482,1)-(503,101))
  ValExprImpls.CAF:lvl2_r1J4E (<no location info>)
```

Is this the expected behavior of the stepper?

**Comment by pjljvandelaar** [comment]
TorXakis requires the hidden communication to be unique. The constraint x>0 has multiple answers so I expected an error message. 
The crash is unexpected!
Look into it coming week.

**Comment by pjljvandelaar** [comment]
The error message is:
`TXS Subst compSubst: incomplete`.
We are encountering a variable that has no substitution defined: yet we are completely substituting...

Looking into the details, I found the substitution map is SURPRISINGLY empty:
```
txsserver.exe: TXS Subst compSubst: incomplete - VarId {name = "x", unid = 1048, varsort = SortId {name = "Int", unid = 102}} not in fromList []
```

**Comment by pjljvandelaar** [comment]
The model is wrong, yet that is not detected!
HiddenChannel is defined as a Channel without data, yet a value is passed
```
PROCDEF p [ A ] ( y :: Int ) ::=
    HIDE [ HiddenChannel ] IN A | HiddenChannel ? x :: Int [[ x > 0 ]] >-> p [ A ] ( y + x ) NI
ENDDEF
```
changing to
```
PROCDEF p [ A ] ( y :: Int ) ::=
    HIDE [ HiddenChannel :: Int ] IN A | HiddenChannel ? x :: Int [[ x > 0 ]] >-> p [ A ] ( y + x ) NI
ENDDEF
```
works fine!

**Comment by pjljvandelaar** [comment]
We will have to investigate why the compiler did not find this issue.
@ikbendedjurre Did you really get this code (than the pretty printer is also wrong) or did you make some changes?

**Comment by ikbendedjurre** [comment]
> HiddenChannel is defined as a Channel without data, yet a value is passed

Ah, of course! I missed that.

> @ikbendedjurre Did you really get this code (than the pretty printer is also wrong) or did you make some changes?

I used my own pretty printer (it has some advantages); the `show procdef` functionality of TorXakis correctly inserts the required `:: Int`.

> We will have to investigate why the compiler did not find this issue.

It would indeed be good if TorXakis would not accept models with this problem.
Shall I leave this issue open until this is the case?

**Comment by pjljvandelaar** [comment]
@ikbendedjurre Yes leave it open!

**Comment by pjljvandelaar** [comment]
Similar issue with wrong number of arguments in procdef
```
PROCDEF p [ A :: Int ] () ::=
    A ? x ? y  -- last ?y is illegal yet error message is not on the spot
ENDDEF

CHANDEF Chans ::=
    X :: Int
ENDDEF

MODELDEF Model ::=
    CHAN IN
    CHAN OUT X
    BEHAVIOUR p [ X ] ()
ENDDEF
```
```
TXS >>  TorXakis :: Model-Based Testing
TXS >>  txsserver starting: "PC-17716.tsn.tno.nl" : 57614
TXS >>  Error {_errorType = Undefined Process, _errorLoc = NoErrorLoc, _errorMsg = "[Error {_errorType = Undefined Entity, _errorLoc = NoErrorLoc, _errorMsg = \"Could not find key Loc {line = 2, start = 13, locUid = 1006} of type Loc VarDeclE when looking for a value of type Proxy * SortId\"}]"}
TXS >>  CallStack (from HasCallStack):
TXS >>  error, called at src\TorXakis\Compiler.hs:175:25 in txs-compiler-0.1.0.0-7vzp3rudL3QHrzstlix9kK:TorXakis.Compiler
```
