### ISSUE TITLE
Keywords not recognized as tokens by own (lc/uc)identifier function

### ISSUE THREAD

**Issue by pjljvandelaar** [TorXakis/TorXakis#866]
The parser doesn't use a tokenizer.
When we want to relax the constraints on some identifiers (e.g. from `lcIdentifier` to `identifier`) we might run in some compatibility issues.
For example
```
STAUTDEF myStautDef [I]() ::=
        STATE s0,s1
        VAR
	INIT s0
	TRANS
		s0 -> I -> s1
ENDDEF
```
will no longer be parsed, since `INIT` is recognised as a possible variable name while it should be a token/keyword.
This particular issue can of course also be solved by demanding that `VAR` is always followed by at least ONE variable.

**Comment by ghost** [comment]
Demanding that INIT is followed by an identifier prevents the user from working with patterns.

**Comment by pjljvandelaar** [comment]
This issue is relevant for #353: less restrictions on the names is desired by code generators that translate a DSL to TorXakis (and the TorXakis results back to the DSL) since it prevents name mapping between DSL and TorXakis.

The change for the particular issue affects `VAR` and **not** `INIT`. In particular the definition of [StautDef@wiki](https://github.com/TorXakis/TorXakis/wiki/StautDef) should be changed from `"VAR" neVarDeclList?`  to `"VAR" neVarDeclList`, i.e. removing the _no variable case_. And indeed, humans and code generators then have to check whether they want to add variables before add the `VAR` keyword. But this is less of an issue than #353 imho. Yet, in the end we might want BOTH.

@HarmMunkESI Is this what you mean by working with patterns?

**Comment by pjljvandelaar** [comment]
Confused...

I found that [makeTokenParser](http://hackage.haskell.org/package/parsec-3.1.13.0/docs/Text-Parsec-Token.html#v:makeTokenParser) is used, with reservedNames include 
```
    , "VAR"
    , "STATE"
    , "INIT"
```
So don't understand why `VAR {- no vars -} INIT` fails to parse.

**Comment by pjljvandelaar** [comment]
Instead of `identity` from Parsec an own `identity` function is made which ignores keywords.

**Comment by pjljvandelaar** [comment]
To illustrate the new title:
```
CHANDEF Chans ::= Out, ENDDEF, INIT, In   :: Int
ENDDEF
``` 
is parsed by torxakis
```
PS C:\TorXakis.experiments> torxakis .\Identifier.txs

TXS >>  TorXakis :: Model-Based Testing

TXS >>  txsserver starting: localhost : 62753
TXS >>  Solver "z3" initialized : Z3 [4.8.5 - build hashcode 14f3ff0b6325]
TXS >>  TxsCore initialized
TXS >>  input files parsed:
TXS >>  .\Identifier.txs
TXS >>
```

**Comment by pjljvandelaar** [comment]
[ParSec](http://hackage.haskell.org/package/parsec/docs/Text-Parsec-Prim.html) states
```Both reserved words and identifiers are a sequence of letters. Whenever we expect a certain reserved word where we can also expect an identifier we have to use the try combinator. ```
So even more investigation need to see how reserved words are to be treated...
