### ISSUE TITLE
Selecting a random element of a list (unfoldCTbranch)

### ISSUE THREAD

**Issue by thburghout** [TorXakis/TorXakis#875]
Hi all!

I'm trying to select a random element of a list in the following PROCDEF

```
PROCDEF DoSystem [In :: Letter; Out :: Letter ] ( list :: List_Letter )
    ::= HIDE [ L :: Letter ] IN
        L ? letter [[ in(letter, list) ]]
        >-> In ! letter
        >-> DoSystem[In, Out] (list)
     NI
ENDDEF
```

However executing `tester Model Harness` yields `unfoldCTbranch: Not unique`. I'm not sure what this error indicates, since I know there's no unique path.

The above PROCDEF does work for empty and singleton lists, but yields unfoldCTbranch for lists with two elements or more.

Is there an alternative method for selecting a random element?

The full code can be found here: https://gist.github.com/thburghout/71a0b58e94bd3994d3344a5bb988b6d4

I was not sure whether this is the right place to post this question. Please indicate if it's more appropriate to email privately.

Thanks!

**Comment by pjljvandelaar** [comment]
TorXakis requires that all hidden communication has unique solutions to limited the states in which the system can be. In your case when the list contains multiple elements, the solution is indeed not unique.

However, I think the main problem is that you are using TorXakis as a programming language.
Yet TorXakis is a specification language!

I think your system is well described using [synchronous communication](https://github.com/TorXakis/TorXakis/wiki/Synchronous_Operator) to make the hidden communication unique by
```
PROCDEF DoSystem [In :: Letter; Out :: Letter ] ( list :: List_Letter ) ::= 
    HIDE [ L :: Letter ] IN
        L ? letter [[ in(letter, list) ]] | In ! letter
        >-> DoSystem[In, Out] (list)
    NI
ENDDEF
```
or even without a hidden channel
```
PROCDEF DoSystem [In :: Letter; Out :: Letter ] ( list :: List_Letter ) ::= 
            In ? letter  [[ in(letter, list) ]]
        >-> DoSystem[In, Out] (list)
ENDDEF
```
In this case, TorXakis will generate test cases for you and select an element from the list at random.
The performance might be very poor by the way.
E.g. when the list contains only "appelflap" and "grandmother", randomly generating a string that full-fill this requirement might take some time.
So you might want to look for alternatives, such as introducing an index to pick the nth element of the list. In that case you might still need a hidden channel to introduce the index.

Please close the issue when this answer solves your problem!
And feel free to ask for more explanation when needed!

**Comment by thburghout** [comment]
Thank you for pointing me in the right direction! Your sample without hidden channel worked great. I now realise that I was looking in the wrong direction indeed. 

```
PROCDEF DoSystem [In :: Letter; Out :: Letter ] ( list :: List_Letter ) ::= 
            In ? letter  [[ in(letter, list) ]]
        >-> DoSystem[In, Out] (list)
ENDDEF
```

I am taking care of minimizing the usage of strings, so I do not think the performance will be an issue in this case. I did take note of it, so if it comes up anyway I now what to do.

Thanks!
