### ISSUE TITLE
Call multiple processes from list structure

### ISSUE THREAD

**Issue by thburghout** [TorXakis/TorXakis#888]
Hi,

I'm trying to call a process for each element in a list. For this I am using a process which handles the base case (NilList) with EXIT and the other case by invoking another process followed by a recursive call on the remaining list.

Since these are behavior expressions I'm using the guard operator to differentiate on the cases. However, it seems that both branches are evaluated regardless of the guard. This yields runtime errors on accessing an element of the empty list in the second branch.

Is there another approach for this?

Eventually the recursive process must be invoked in parallel since the order of the processes is not important.

The following process definition yields a runtime error (providing an empty list of switches);

```
PROCDEF SwitchesAreShifted  [ SimOut :: Notification ]
                            ( switches :: List_Element; states :: List_Status; elements :: List_Element ) EXIT
    ::=
    LET more = isList_Element(switches) IN
        [[ not(more) ]]
        =>> EXIT
    ##
        [[ more ]]
        =>> SingleSwitchIsShifted [ SimOut ] (opposite(status(elemId(e_head(switches)), states)))
        >>> SwitchesAreShifted [SimOut] (e_tail(switches), states, elements)
    NI
ENDDEF
```

Replacing all evaluations of the element by if, then, elses resolves the issue:

```
PROCDEF SwitchesAreShifted  [ SimOut :: Notification ]
                            ( switches :: List_Element; states :: List_Status; elements :: List_Element ) EXIT
    ::=
    LET more = isList_Element(switches) IN
        [[ not(more) ]]
        =>> EXIT
    ##
        [[ more ]]
        =>> SingleSwitchIsShifted [ SimOut ] (opposite( IF more THEN
                                                            status(elemId(e_head(switches)), states)
                                                        ELSE invalidSwitchStatus FI ))
        >>> SwitchesAreShifted [SimOut] (IF more THEN e_tail(switches) ELSE NilList_Element FI,
                                         states, elements)
    NI
ENDDEF
```

However, this solution hardly seems elegant. It can still be improved by using LET expressions for this. Still, is there some other solution I'm missing here?

**Comment by pjljvandelaar** [comment]
As is written in the wiki: https://github.com/TorXakis/TorXakis/wiki/Function, one needs to protect access operators by ensuring they are only applied to a structure created with the corresponding constructor.

However the guard should be sufficient protection (in Expand.hs):
```
expand chsets (BNbexpr we (TxsDefs.view -> Guard c bexp))  = do
    tds <- gets IOB.tdefs
    case ValExpr.eval $ ValExpr.subst (Map.map cstrConst we) (funcDefs tds) c of
        Right (Cbool True)  -> expand chsets (BNbexpr we bexp)
        Right (Cbool False) -> return []
        _                   -> do IOB.putMsgs [ EnvData.TXS_CORE_MODEL_ERROR
                                                "Expand: guard does not evaluate to a boolean" ]
                                  return []
```

I tried to reconstruct your bug, as follows:
```
TYPEDEF List ::= Nil
                | Cstr { head :: Int; tail :: List }
ENDDEF

PROCDEF P [A :: Int] (x :: Int) ::=
    A ! x >-> P[A](x)
ENDDEF

PROCDEF StartPs [A :: Int] (ps :: List) ::=
        [[ isCstr (ps) ]] =>> (     P[A](head(ps))
                                |||
                                    StartPs[A](tail(ps))
                              )
        
ENDDEF

CHANDEF Chans ::=
    A :: Int
ENDDEF

MODELDEF Model ::=
    CHAN IN 
    CHAN OUT A
    BEHAVIOUR StartPs [A] (Cstr(7, Cstr(4, Cstr(1,Nil))))
ENDDEF
```
But this works fine:
```
TXS >> stepper Model
TXS >>  Stepper started
TXS >> step 10
TXS >>  .....1: Act { { ( A, [ 4 ] ) } }
TXS >>  .....2: Act { { ( A, [ 7 ] ) } }
TXS >>  .....3: Act { { ( A, [ 7 ] ) } }
TXS >>  .....4: Act { { ( A, [ 4 ] ) } }
TXS >>  .....5: Act { { ( A, [ 1 ] ) } }
TXS >>  .....6: Act { { ( A, [ 7 ] ) } }
TXS >>  .....7: Act { { ( A, [ 1 ] ) } }
TXS >>  .....8: Act { { ( A, [ 4 ] ) } }
TXS >>  .....9: Act { { ( A, [ 1 ] ) } }
TXS >>  ....10: Act { { ( A, [ 7 ] ) } }
TXS >>  PASS
```

This made me realize the problem was somewhere else...
You have assumed wrong binding / priority of the operators.
I think you want
```
PROCDEF SwitchesAreShifted  [ SimOut :: Notification ]
                            ( switches :: List_Element; states :: List_Status; elements :: List_Element ) EXIT
    ::=
    LET more = isList_Element(switches) IN
        [[ not(more) ]]
        =>> EXIT
    ##
        [[ more ]]
        =>> ( SingleSwitchIsShifted [ SimOut ] (opposite(status(elemId(e_head(switches)), states)))
                   >>> SwitchesAreShifted [SimOut] (e_tail(switches), states, elements)
                 )
    NI
ENDDEF
```
Otherwise, `SwitchesAreShifted` are also called after the `[[not(more)]] EXIT` branch: causing the unwanted, yet observed behaviour.

Please close the issue if this indeed solves your problem!

**Comment by thburghout** [comment]
I was aware of the fact that I needed to protect the accessors properly. I thought I was doing so with the guards. Apparently I got the associativity wrong, thank you for pointing that out! I tested it, and it works as expected now. Thanks!
