### ISSUE TITLE
Undefined Function at <no location>

### ISSUE THREAD

**Issue by gitLabor8** [TorXakis/TorXakis#944]
Current behaviour: upon compiling [https://pastebin.com/r7hLLC9Q](https://pastebin.com/r7hLLC9Q) I get the following error message:
>TXS >>  TorXakis :: Model-Based Testing
> 
> TXS >>  txsserver starting: "Braeburn" : 52914
> TXS >>  Undefined Function at \<no location>: Could not determine the function based on the given signature
> TXS >>  CallStack (from HasCallStack):
> TXS >>  error, called at src\TorXakis\Compiler.hs:175:25 in txs-compiler-0.1.0.0-5W17IXBVyzQ39twEH6isyB:TorXakis.Compiler

Expected behaviour: An error message with a function name, keyword and/or line number that hints at where to look for an error.

Note: This is my first time at TorXakis and the program doesn't look that complex, so the bug is probably easy to spot with the eye for a veteran.

**Comment by tretmans** [comment]
In CNECTDEF sim,
Line 66:      DECODE    Input  ! fromString <- ? s
should be:    DECODE    Input  ! fromString(s) <- ? s

The error message should at least contain a line number.
[undefined.txt](https://github.com/TorXakis/TorXakis/files/3939576/undefined.txt)

**Comment by pjljvandelaar** [comment]
Seems that our compiler has no location info in these situation:
https://github.com/TorXakis/TorXakis/blob/develop/sys/txs-compiler/src/TorXakis/Compiler/Maps.hs#L136
@dnadales Do you agree we should pass the location as an additional parameter?

**Comment by dnadales** [comment]
> @dnadales Do you agree we should pass the location as an additional parameter?

Sure.

**Comment by pjljvandelaar** [comment]
Bug solved:  Undefined Function at line 66 and column 25: Could not determine the function based on the given signature
